/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData{}

// PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData struct for PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData
type PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData struct {

	// Exit status, if available.
	Exitstatus *string `json:"exitstatus,omitempty"`

	// Task id.
	Id *string `json:"id,omitempty"`

	// Node the task is running on.
	Node string `json:"node"`

	// The Unix PID
	Pid int64 `json:"pid"`

	// The task start time (Epoch)
	Pstart int64 `json:"pstart"`

	// The task's start time.
	Starttime int64 `json:"starttime"`

	// Whether a task is still running.
	Status PdmPbsRemotesStatusEnum `json:"status"`

	// The task type.
	Type string `json:"type"`

	// The task's UPID.
	Upid string `json:"upid"`

	// The authenticated entity who started the task.
	User string `json:"user"`

	AdditionalProperties map[string]interface{}
}

type _PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData

// NewPbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData instantiates a new PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData(node string, pid int64, pstart int64, starttime int64, status PdmPbsRemotesStatusEnum, type_ string, upid string, user string) *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData {
	this := PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData{}
	this.Node = node
	this.Pid = pid
	this.Pstart = pstart
	this.Starttime = starttime
	this.Status = status
	this.Type = type_
	this.Upid = upid
	this.User = user
	return &this
}

// NewPbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseDataWithDefaults instantiates a new PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseDataWithDefaults() *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData {
	this := PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData{}











	return &this
}


// GetExitstatus returns the Exitstatus field value if set, zero value otherwise.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetExitstatus() string {
	if o == nil || IsNil(o.Exitstatus) {
		var ret string
		return ret
	}
	return *o.Exitstatus
}

// GetExitstatusOk returns a tuple with the Exitstatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetExitstatusOk() (*string, bool) {
	if o == nil || IsNil(o.Exitstatus) {
		return nil, false
	}
	return o.Exitstatus, true
}

// HasExitstatus returns a boolean if a field has been set.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) HasExitstatus() bool {
	if o != nil && !IsNil(o.Exitstatus) {
		return true
	}

	return false
}

// SetExitstatus gets a reference to the given string and assigns it to the Exitstatus field.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) SetExitstatus(v string) {
	o.Exitstatus = &v
}


// GetId returns the Id field value if set, zero value otherwise.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) SetId(v string) {
	o.Id = &v
}


// GetNode returns the Node field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetNode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Node
}

// GetNodeOk returns a tuple with the Node field value
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetNodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Node, true
}

// SetNode sets field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) SetNode(v string) {
	o.Node = v
}


// GetPid returns the Pid field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetPid() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Pid
}

// GetPidOk returns a tuple with the Pid field value
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetPidOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pid, true
}

// SetPid sets field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) SetPid(v int64) {
	o.Pid = v
}


// GetPstart returns the Pstart field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetPstart() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Pstart
}

// GetPstartOk returns a tuple with the Pstart field value
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetPstartOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pstart, true
}

// SetPstart sets field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) SetPstart(v int64) {
	o.Pstart = v
}


// GetStarttime returns the Starttime field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetStarttime() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Starttime
}

// GetStarttimeOk returns a tuple with the Starttime field value
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetStarttimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Starttime, true
}

// SetStarttime sets field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) SetStarttime(v int64) {
	o.Starttime = v
}


// GetStatus returns the Status field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetStatus() PdmPbsRemotesStatusEnum {
	if o == nil {
		var ret PdmPbsRemotesStatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetStatusOk() (*PdmPbsRemotesStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) SetStatus(v PdmPbsRemotesStatusEnum) {
	o.Status = v
}


// GetType returns the Type field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) SetType(v string) {
	o.Type = v
}


// GetUpid returns the Upid field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetUpid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Upid
}

// GetUpidOk returns a tuple with the Upid field value
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetUpidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Upid, true
}

// SetUpid sets field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) SetUpid(v string) {
	o.Upid = v
}


// GetUser returns the User field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) SetUser(v string) {
	o.User = v
}


func (o PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Exitstatus) {
		toSerialize["exitstatus"] = o.Exitstatus
	}
	
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	
	toSerialize["node"] = o.Node
	
	toSerialize["pid"] = o.Pid
	
	toSerialize["pstart"] = o.Pstart
	
	toSerialize["starttime"] = o.Starttime
	
	toSerialize["status"] = o.Status
	
	toSerialize["type"] = o.Type
	
	toSerialize["upid"] = o.Upid
	
	toSerialize["user"] = o.User
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node",
		"pid",
		"pstart",
		"starttime",
		"status",
		"type",
		"upid",
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData := _PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData{}

	err = json.Unmarshal(data, &varPbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData)

	if err != nil {
		return err
	}

	*o = PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData(varPbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "exitstatus")
		delete(additionalProperties, "id")
		delete(additionalProperties, "node")
		delete(additionalProperties, "pid")
		delete(additionalProperties, "pstart")
		delete(additionalProperties, "starttime")
		delete(additionalProperties, "status")
		delete(additionalProperties, "type")
		delete(additionalProperties, "upid")
		delete(additionalProperties, "user")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData struct {
	value *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData
	isSet bool
}

func (v NullablePbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) Get() *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData {
	return v.value
}

func (v *NullablePbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) Set(val *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData(val *PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) *NullablePbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData {
	return &NullablePbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData{value: val, isSet: true}
}

func (v NullablePbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


