/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AccessUsersCreateTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessUsersCreateTokenRequest{}

// AccessUsersCreateTokenRequest struct for AccessUsersCreateTokenRequest
type AccessUsersCreateTokenRequest struct {

	// Comment.
	Comment *string `json:"comment,omitempty" validate:"regexp=^[[:^cntrl:]]*$"`

	// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty" validate:"regexp=^[a-f0-9]{64}$"`

	// Enable the account (default). You can set this to '0' to disable the account.
	Enable *bool `json:"enable,omitempty"`

	// Account expiration date (seconds since epoch). '0' means no expiration date.
	Expire *int64 `json:"expire,omitempty"`

}

// NewAccessUsersCreateTokenRequest instantiates a new AccessUsersCreateTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessUsersCreateTokenRequest() *AccessUsersCreateTokenRequest {
	this := AccessUsersCreateTokenRequest{}
	var enable bool = true
	this.Enable = &enable
	var expire int64 = 0
	this.Expire = &expire
	return &this
}

// NewAccessUsersCreateTokenRequestWithDefaults instantiates a new AccessUsersCreateTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessUsersCreateTokenRequestWithDefaults() *AccessUsersCreateTokenRequest {
	this := AccessUsersCreateTokenRequest{}



	var enable bool = true
	this.Enable = &enable

	var expire int64 = 0
	this.Expire = &expire

	return &this
}


// GetComment returns the Comment field value if set, zero value otherwise.
func (o *AccessUsersCreateTokenRequest) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersCreateTokenRequest) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *AccessUsersCreateTokenRequest) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *AccessUsersCreateTokenRequest) SetComment(v string) {
	o.Comment = &v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *AccessUsersCreateTokenRequest) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersCreateTokenRequest) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *AccessUsersCreateTokenRequest) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *AccessUsersCreateTokenRequest) SetDigest(v string) {
	o.Digest = &v
}


// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *AccessUsersCreateTokenRequest) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersCreateTokenRequest) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *AccessUsersCreateTokenRequest) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *AccessUsersCreateTokenRequest) SetEnable(v bool) {
	o.Enable = &v
}


// GetExpire returns the Expire field value if set, zero value otherwise.
func (o *AccessUsersCreateTokenRequest) GetExpire() int64 {
	if o == nil || IsNil(o.Expire) {
		var ret int64
		return ret
	}
	return *o.Expire
}

// GetExpireOk returns a tuple with the Expire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersCreateTokenRequest) GetExpireOk() (*int64, bool) {
	if o == nil || IsNil(o.Expire) {
		return nil, false
	}
	return o.Expire, true
}

// HasExpire returns a boolean if a field has been set.
func (o *AccessUsersCreateTokenRequest) HasExpire() bool {
	if o != nil && !IsNil(o.Expire) {
		return true
	}

	return false
}

// SetExpire gets a reference to the given int64 and assigns it to the Expire field.
func (o *AccessUsersCreateTokenRequest) SetExpire(v int64) {
	o.Expire = &v
}


func (o AccessUsersCreateTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessUsersCreateTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	
	if !IsNil(o.Expire) {
		toSerialize["expire"] = o.Expire
	}
	
	return toSerialize, nil
}

type NullableAccessUsersCreateTokenRequest struct {
	value *AccessUsersCreateTokenRequest
	isSet bool
}

func (v NullableAccessUsersCreateTokenRequest) Get() *AccessUsersCreateTokenRequest {
	return v.value
}

func (v *NullableAccessUsersCreateTokenRequest) Set(val *AccessUsersCreateTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessUsersCreateTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessUsersCreateTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessUsersCreateTokenRequest(val *AccessUsersCreateTokenRequest) *NullableAccessUsersCreateTokenRequest {
	return &NullableAccessUsersCreateTokenRequest{value: val, isSet: true}
}

func (v NullableAccessUsersCreateTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessUsersCreateTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


