/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PdmMpField - struct for PdmMpField
type PdmMpField struct {
	PdmLogRatelimitConfig *PdmLogRatelimitConfig
	String *string
}

// PdmLogRatelimitConfigAsPdmMpField is a convenience function that returns PdmLogRatelimitConfig wrapped in PdmMpField
func PdmLogRatelimitConfigAsPdmMpField(v *PdmLogRatelimitConfig) PdmMpField {
	return PdmMpField{
		PdmLogRatelimitConfig: v,
	}
}

// stringAsPdmMpField is a convenience function that returns string wrapped in PdmMpField
func StringAsPdmMpField(v *string) PdmMpField {
	return PdmMpField{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PdmMpField) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PdmLogRatelimitConfig
	err = newStrictDecoder(data).Decode(&dst.PdmLogRatelimitConfig)
	if err == nil {
		jsonPdmLogRatelimitConfig, _ := json.Marshal(dst.PdmLogRatelimitConfig)
		if string(jsonPdmLogRatelimitConfig) == "{}" { // empty struct
			dst.PdmLogRatelimitConfig = nil
		} else {
			if err = validator.Validate(dst.PdmLogRatelimitConfig); err != nil {
				dst.PdmLogRatelimitConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.PdmLogRatelimitConfig = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PdmLogRatelimitConfig = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PdmMpField)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PdmMpField)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PdmMpField) MarshalJSON() ([]byte, error) {
	if src.PdmLogRatelimitConfig != nil {
		return json.Marshal(&src.PdmLogRatelimitConfig)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PdmMpField) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PdmLogRatelimitConfig != nil {
		return obj.PdmLogRatelimitConfig
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PdmMpField) GetActualInstanceValue() (interface{}) {
	if obj.PdmLogRatelimitConfig != nil {
		return *obj.PdmLogRatelimitConfig
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePdmMpField struct {
	value *PdmMpField
	isSet bool
}

func (v NullablePdmMpField) Get() *PdmMpField {
	return v.value
}

func (v *NullablePdmMpField) Set(val *PdmMpField) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmMpField) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmMpField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmMpField(val *PdmMpField) *NullablePdmMpField {
	return &NullablePdmMpField{value: val, isSet: true}
}

func (v NullablePdmMpField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmMpField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


