/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NodesConfigUpdateConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesConfigUpdateConfigRequest{}

// NodesConfigUpdateConfigRequest struct for NodesConfigUpdateConfigRequest
type NodesConfigUpdateConfigRequest struct {

	// OpenSSL cipher list used by the api server for TLS <= 1.2
	CiphersTls12 *string `json:"ciphers-tls-1.2,omitempty" validate:"regexp=^[0-9A-Za-z_:, +!\\\\-@=.]+$"`

	// OpenSSL ciphersuites list used by the api server for TLS 1.3
	CiphersTls13 *string `json:"ciphers-tls-1.3,omitempty" validate:"regexp=^[0-9A-Za-z_:, +!\\\\-@=.]+$"`

	// All available languages in Proxmox. Taken from proxmox-i18n repository. pt_BR, zh_CN, and zh_TW use the same case in the translation files.
	DefaultLang *PdmDefaultLangEnum `json:"default-lang,omitempty"`

	// List of properties to delete.
	Delete []PdmNodesConfigInlineEnum `json:"delete,omitempty"`

	// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty" validate:"regexp=^[a-f0-9]{64}$"`

	// E-Mail Address.
	EmailFrom *string `json:"email-from,omitempty" validate:"regexp=^[[:^cntrl:]]*$"`

	// HTTP proxy configuration [http://]<host>[:port]
	HttpProxy *string `json:"http-proxy,omitempty"`

}

// NewNodesConfigUpdateConfigRequest instantiates a new NodesConfigUpdateConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesConfigUpdateConfigRequest() *NodesConfigUpdateConfigRequest {
	this := NodesConfigUpdateConfigRequest{}
	return &this
}

// NewNodesConfigUpdateConfigRequestWithDefaults instantiates a new NodesConfigUpdateConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesConfigUpdateConfigRequestWithDefaults() *NodesConfigUpdateConfigRequest {
	this := NodesConfigUpdateConfigRequest{}








	return &this
}


// GetCiphersTls12 returns the CiphersTls12 field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetCiphersTls12() string {
	if o == nil || IsNil(o.CiphersTls12) {
		var ret string
		return ret
	}
	return *o.CiphersTls12
}

// GetCiphersTls12Ok returns a tuple with the CiphersTls12 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetCiphersTls12Ok() (*string, bool) {
	if o == nil || IsNil(o.CiphersTls12) {
		return nil, false
	}
	return o.CiphersTls12, true
}

// HasCiphersTls12 returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasCiphersTls12() bool {
	if o != nil && !IsNil(o.CiphersTls12) {
		return true
	}

	return false
}

// SetCiphersTls12 gets a reference to the given string and assigns it to the CiphersTls12 field.
func (o *NodesConfigUpdateConfigRequest) SetCiphersTls12(v string) {
	o.CiphersTls12 = &v
}


// GetCiphersTls13 returns the CiphersTls13 field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetCiphersTls13() string {
	if o == nil || IsNil(o.CiphersTls13) {
		var ret string
		return ret
	}
	return *o.CiphersTls13
}

// GetCiphersTls13Ok returns a tuple with the CiphersTls13 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetCiphersTls13Ok() (*string, bool) {
	if o == nil || IsNil(o.CiphersTls13) {
		return nil, false
	}
	return o.CiphersTls13, true
}

// HasCiphersTls13 returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasCiphersTls13() bool {
	if o != nil && !IsNil(o.CiphersTls13) {
		return true
	}

	return false
}

// SetCiphersTls13 gets a reference to the given string and assigns it to the CiphersTls13 field.
func (o *NodesConfigUpdateConfigRequest) SetCiphersTls13(v string) {
	o.CiphersTls13 = &v
}


// GetDefaultLang returns the DefaultLang field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetDefaultLang() PdmDefaultLangEnum {
	if o == nil || IsNil(o.DefaultLang) {
		var ret PdmDefaultLangEnum
		return ret
	}
	return *o.DefaultLang
}

// GetDefaultLangOk returns a tuple with the DefaultLang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetDefaultLangOk() (*PdmDefaultLangEnum, bool) {
	if o == nil || IsNil(o.DefaultLang) {
		return nil, false
	}
	return o.DefaultLang, true
}

// HasDefaultLang returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasDefaultLang() bool {
	if o != nil && !IsNil(o.DefaultLang) {
		return true
	}

	return false
}

// SetDefaultLang gets a reference to the given PdmDefaultLangEnum and assigns it to the DefaultLang field.
func (o *NodesConfigUpdateConfigRequest) SetDefaultLang(v PdmDefaultLangEnum) {
	o.DefaultLang = &v
}


// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetDelete() []PdmNodesConfigInlineEnum {
	if o == nil || IsNil(o.Delete) {
		var ret []PdmNodesConfigInlineEnum
		return ret
	}
	return o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetDeleteOk() ([]PdmNodesConfigInlineEnum, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given []PdmNodesConfigInlineEnum and assigns it to the Delete field.
func (o *NodesConfigUpdateConfigRequest) SetDelete(v []PdmNodesConfigInlineEnum) {
	o.Delete = v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *NodesConfigUpdateConfigRequest) SetDigest(v string) {
	o.Digest = &v
}


// GetEmailFrom returns the EmailFrom field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetEmailFrom() string {
	if o == nil || IsNil(o.EmailFrom) {
		var ret string
		return ret
	}
	return *o.EmailFrom
}

// GetEmailFromOk returns a tuple with the EmailFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetEmailFromOk() (*string, bool) {
	if o == nil || IsNil(o.EmailFrom) {
		return nil, false
	}
	return o.EmailFrom, true
}

// HasEmailFrom returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasEmailFrom() bool {
	if o != nil && !IsNil(o.EmailFrom) {
		return true
	}

	return false
}

// SetEmailFrom gets a reference to the given string and assigns it to the EmailFrom field.
func (o *NodesConfigUpdateConfigRequest) SetEmailFrom(v string) {
	o.EmailFrom = &v
}


// GetHttpProxy returns the HttpProxy field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetHttpProxy() string {
	if o == nil || IsNil(o.HttpProxy) {
		var ret string
		return ret
	}
	return *o.HttpProxy
}

// GetHttpProxyOk returns a tuple with the HttpProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetHttpProxyOk() (*string, bool) {
	if o == nil || IsNil(o.HttpProxy) {
		return nil, false
	}
	return o.HttpProxy, true
}

// HasHttpProxy returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasHttpProxy() bool {
	if o != nil && !IsNil(o.HttpProxy) {
		return true
	}

	return false
}

// SetHttpProxy gets a reference to the given string and assigns it to the HttpProxy field.
func (o *NodesConfigUpdateConfigRequest) SetHttpProxy(v string) {
	o.HttpProxy = &v
}


func (o NodesConfigUpdateConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesConfigUpdateConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.CiphersTls12) {
		toSerialize["ciphers-tls-1.2"] = o.CiphersTls12
	}
	
	if !IsNil(o.CiphersTls13) {
		toSerialize["ciphers-tls-1.3"] = o.CiphersTls13
	}
	
	if !IsNil(o.DefaultLang) {
		toSerialize["default-lang"] = o.DefaultLang
	}
	
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	if !IsNil(o.EmailFrom) {
		toSerialize["email-from"] = o.EmailFrom
	}
	
	if !IsNil(o.HttpProxy) {
		toSerialize["http-proxy"] = o.HttpProxy
	}
	
	return toSerialize, nil
}

type NullableNodesConfigUpdateConfigRequest struct {
	value *NodesConfigUpdateConfigRequest
	isSet bool
}

func (v NullableNodesConfigUpdateConfigRequest) Get() *NodesConfigUpdateConfigRequest {
	return v.value
}

func (v *NullableNodesConfigUpdateConfigRequest) Set(val *NodesConfigUpdateConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesConfigUpdateConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesConfigUpdateConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesConfigUpdateConfigRequest(val *NodesConfigUpdateConfigRequest) *NullableNodesConfigUpdateConfigRequest {
	return &NullableNodesConfigUpdateConfigRequest{value: val, isSet: true}
}

func (v NullableNodesConfigUpdateConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesConfigUpdateConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


