/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigAccessUpdateWebauthnRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigAccessUpdateWebauthnRequest{}

// ConfigAccessUpdateWebauthnRequest struct for ConfigAccessUpdateWebauthnRequest
type ConfigAccessUpdateWebauthnRequest struct {

	// If an `origin` is specified, this specifies whether subdomains should be considered valid as well.  May be changed at any time.  Defaults to `true`.
	AllowSubdomains *bool `json:"allow-subdomains,omitempty"`

	// List of properties to delete.
	Delete []PdmConfigAccessInlineEnum2 `json:"delete,omitempty"`

	// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty" validate:"regexp=^[a-f0-9]{64}$"`

	// Relying party ID. Must be the domain name without protocol, port or location.  Changing this *will* break existing credentials.
	Id *string `json:"id,omitempty"`

	// Site origin. Must be a `https://` URL (or `http://localhost`). Should contain the address users type in their browsers to access the web interface.  Changing this *may* break existing credentials.
	Origin *string `json:"origin,omitempty"`

	// Relying party name. Any text identifier.  Changing this *may* break existing credentials.
	Rp *string `json:"rp,omitempty"`

}

// NewConfigAccessUpdateWebauthnRequest instantiates a new ConfigAccessUpdateWebauthnRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigAccessUpdateWebauthnRequest() *ConfigAccessUpdateWebauthnRequest {
	this := ConfigAccessUpdateWebauthnRequest{}
	return &this
}

// NewConfigAccessUpdateWebauthnRequestWithDefaults instantiates a new ConfigAccessUpdateWebauthnRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigAccessUpdateWebauthnRequestWithDefaults() *ConfigAccessUpdateWebauthnRequest {
	this := ConfigAccessUpdateWebauthnRequest{}







	return &this
}


// GetAllowSubdomains returns the AllowSubdomains field value if set, zero value otherwise.
func (o *ConfigAccessUpdateWebauthnRequest) GetAllowSubdomains() bool {
	if o == nil || IsNil(o.AllowSubdomains) {
		var ret bool
		return ret
	}
	return *o.AllowSubdomains
}

// GetAllowSubdomainsOk returns a tuple with the AllowSubdomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessUpdateWebauthnRequest) GetAllowSubdomainsOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowSubdomains) {
		return nil, false
	}
	return o.AllowSubdomains, true
}

// HasAllowSubdomains returns a boolean if a field has been set.
func (o *ConfigAccessUpdateWebauthnRequest) HasAllowSubdomains() bool {
	if o != nil && !IsNil(o.AllowSubdomains) {
		return true
	}

	return false
}

// SetAllowSubdomains gets a reference to the given bool and assigns it to the AllowSubdomains field.
func (o *ConfigAccessUpdateWebauthnRequest) SetAllowSubdomains(v bool) {
	o.AllowSubdomains = &v
}


// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *ConfigAccessUpdateWebauthnRequest) GetDelete() []PdmConfigAccessInlineEnum2 {
	if o == nil || IsNil(o.Delete) {
		var ret []PdmConfigAccessInlineEnum2
		return ret
	}
	return o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessUpdateWebauthnRequest) GetDeleteOk() ([]PdmConfigAccessInlineEnum2, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *ConfigAccessUpdateWebauthnRequest) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given []PdmConfigAccessInlineEnum2 and assigns it to the Delete field.
func (o *ConfigAccessUpdateWebauthnRequest) SetDelete(v []PdmConfigAccessInlineEnum2) {
	o.Delete = v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *ConfigAccessUpdateWebauthnRequest) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessUpdateWebauthnRequest) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *ConfigAccessUpdateWebauthnRequest) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *ConfigAccessUpdateWebauthnRequest) SetDigest(v string) {
	o.Digest = &v
}


// GetId returns the Id field value if set, zero value otherwise.
func (o *ConfigAccessUpdateWebauthnRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessUpdateWebauthnRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ConfigAccessUpdateWebauthnRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ConfigAccessUpdateWebauthnRequest) SetId(v string) {
	o.Id = &v
}


// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *ConfigAccessUpdateWebauthnRequest) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessUpdateWebauthnRequest) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *ConfigAccessUpdateWebauthnRequest) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *ConfigAccessUpdateWebauthnRequest) SetOrigin(v string) {
	o.Origin = &v
}


// GetRp returns the Rp field value if set, zero value otherwise.
func (o *ConfigAccessUpdateWebauthnRequest) GetRp() string {
	if o == nil || IsNil(o.Rp) {
		var ret string
		return ret
	}
	return *o.Rp
}

// GetRpOk returns a tuple with the Rp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessUpdateWebauthnRequest) GetRpOk() (*string, bool) {
	if o == nil || IsNil(o.Rp) {
		return nil, false
	}
	return o.Rp, true
}

// HasRp returns a boolean if a field has been set.
func (o *ConfigAccessUpdateWebauthnRequest) HasRp() bool {
	if o != nil && !IsNil(o.Rp) {
		return true
	}

	return false
}

// SetRp gets a reference to the given string and assigns it to the Rp field.
func (o *ConfigAccessUpdateWebauthnRequest) SetRp(v string) {
	o.Rp = &v
}


func (o ConfigAccessUpdateWebauthnRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigAccessUpdateWebauthnRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.AllowSubdomains) {
		toSerialize["allow-subdomains"] = o.AllowSubdomains
	}
	
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}
	
	if !IsNil(o.Rp) {
		toSerialize["rp"] = o.Rp
	}
	
	return toSerialize, nil
}

type NullableConfigAccessUpdateWebauthnRequest struct {
	value *ConfigAccessUpdateWebauthnRequest
	isSet bool
}

func (v NullableConfigAccessUpdateWebauthnRequest) Get() *ConfigAccessUpdateWebauthnRequest {
	return v.value
}

func (v *NullableConfigAccessUpdateWebauthnRequest) Set(val *ConfigAccessUpdateWebauthnRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigAccessUpdateWebauthnRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigAccessUpdateWebauthnRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigAccessUpdateWebauthnRequest(val *ConfigAccessUpdateWebauthnRequest) *NullableConfigAccessUpdateWebauthnRequest {
	return &NullableConfigAccessUpdateWebauthnRequest{value: val, isSet: true}
}

func (v NullableConfigAccessUpdateWebauthnRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigAccessUpdateWebauthnRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


