/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PdmPveRemotesInlineEnum the model 'PdmPveRemotesInlineEnum'
type PdmPveRemotesInlineEnum string

// List of PdmPveRemotesInlineEnum
const (
	PDMPVEREMOTESINLINEENUM_INET PdmPveRemotesInlineEnum = "inet"
	PDMPVEREMOTESINLINEENUM_INET6 PdmPveRemotesInlineEnum = "inet6"
)

// All allowed values of PdmPveRemotesInlineEnum enum
var AllowedPdmPveRemotesInlineEnumEnumValues = []PdmPveRemotesInlineEnum{
	"inet",
	"inet6",
}

func (v *PdmPveRemotesInlineEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PdmPveRemotesInlineEnum(value)
	for _, existing := range AllowedPdmPveRemotesInlineEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PdmPveRemotesInlineEnum", value)
}

// NewPdmPveRemotesInlineEnumFromValue returns a pointer to a valid PdmPveRemotesInlineEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPdmPveRemotesInlineEnumFromValue(v string) (*PdmPveRemotesInlineEnum, error) {
	ev := PdmPveRemotesInlineEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PdmPveRemotesInlineEnum: valid values are %v", v, AllowedPdmPveRemotesInlineEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PdmPveRemotesInlineEnum) IsValid() bool {
	for _, existing := range AllowedPdmPveRemotesInlineEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PdmPveRemotesInlineEnum value
func (v PdmPveRemotesInlineEnum) Ptr() *PdmPveRemotesInlineEnum {
	return &v
}

type NullablePdmPveRemotesInlineEnum struct {
	value *PdmPveRemotesInlineEnum
	isSet bool
}

func (v NullablePdmPveRemotesInlineEnum) Get() *PdmPveRemotesInlineEnum {
	return v.value
}

func (v *NullablePdmPveRemotesInlineEnum) Set(val *PdmPveRemotesInlineEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmPveRemotesInlineEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmPveRemotesInlineEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmPveRemotesInlineEnum(val *PdmPveRemotesInlineEnum) *NullablePdmPveRemotesInlineEnum {
	return &NullablePdmPveRemotesInlineEnum{value: val, isSet: true}
}

func (v NullablePdmPveRemotesInlineEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmPveRemotesInlineEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

