/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesTasksGetLogResponseDataData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesTasksGetLogResponseDataData{}

// NodesTasksGetLogResponseDataData A line of a task log.
type NodesTasksGetLogResponseDataData struct {

	// Line number.
	N int64 `json:"n"`

	// The line of the log.
	T string `json:"t"`

	AdditionalProperties map[string]interface{}
}

type _NodesTasksGetLogResponseDataData NodesTasksGetLogResponseDataData

// NewNodesTasksGetLogResponseDataData instantiates a new NodesTasksGetLogResponseDataData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesTasksGetLogResponseDataData(n int64, t string) *NodesTasksGetLogResponseDataData {
	this := NodesTasksGetLogResponseDataData{}
	this.N = n
	this.T = t
	return &this
}

// NewNodesTasksGetLogResponseDataDataWithDefaults instantiates a new NodesTasksGetLogResponseDataData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesTasksGetLogResponseDataDataWithDefaults() *NodesTasksGetLogResponseDataData {
	this := NodesTasksGetLogResponseDataData{}



	return &this
}


// GetN returns the N field value
func (o *NodesTasksGetLogResponseDataData) GetN() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.N
}

// GetNOk returns a tuple with the N field value
// and a boolean to check if the value has been set.
func (o *NodesTasksGetLogResponseDataData) GetNOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.N, true
}

// SetN sets field value
func (o *NodesTasksGetLogResponseDataData) SetN(v int64) {
	o.N = v
}


// GetT returns the T field value
func (o *NodesTasksGetLogResponseDataData) GetT() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.T
}

// GetTOk returns a tuple with the T field value
// and a boolean to check if the value has been set.
func (o *NodesTasksGetLogResponseDataData) GetTOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.T, true
}

// SetT sets field value
func (o *NodesTasksGetLogResponseDataData) SetT(v string) {
	o.T = v
}


func (o NodesTasksGetLogResponseDataData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesTasksGetLogResponseDataData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["n"] = o.N
	
	toSerialize["t"] = o.T
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesTasksGetLogResponseDataData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"n",
		"t",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesTasksGetLogResponseDataData := _NodesTasksGetLogResponseDataData{}

	err = json.Unmarshal(data, &varNodesTasksGetLogResponseDataData)

	if err != nil {
		return err
	}

	*o = NodesTasksGetLogResponseDataData(varNodesTasksGetLogResponseDataData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "n")
		delete(additionalProperties, "t")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesTasksGetLogResponseDataData struct {
	value *NodesTasksGetLogResponseDataData
	isSet bool
}

func (v NullableNodesTasksGetLogResponseDataData) Get() *NodesTasksGetLogResponseDataData {
	return v.value
}

func (v *NullableNodesTasksGetLogResponseDataData) Set(val *NodesTasksGetLogResponseDataData) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesTasksGetLogResponseDataData) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesTasksGetLogResponseDataData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesTasksGetLogResponseDataData(val *NodesTasksGetLogResponseDataData) *NullableNodesTasksGetLogResponseDataData {
	return &NullableNodesTasksGetLogResponseDataData{value: val, isSet: true}
}

func (v NullableNodesTasksGetLogResponseDataData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesTasksGetLogResponseDataData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


