/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PdmSdnVnetsTypeEnum the model 'PdmSdnVnetsTypeEnum'
type PdmSdnVnetsTypeEnum string

// List of PdmSdnVnetsTypeEnum
const (
	PDMSDNVNETSTYPEENUM_VNET PdmSdnVnetsTypeEnum = "vnet"
)

// All allowed values of PdmSdnVnetsTypeEnum enum
var AllowedPdmSdnVnetsTypeEnumEnumValues = []PdmSdnVnetsTypeEnum{
	"vnet",
}

func (v *PdmSdnVnetsTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PdmSdnVnetsTypeEnum(value)
	for _, existing := range AllowedPdmSdnVnetsTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PdmSdnVnetsTypeEnum", value)
}

// NewPdmSdnVnetsTypeEnumFromValue returns a pointer to a valid PdmSdnVnetsTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPdmSdnVnetsTypeEnumFromValue(v string) (*PdmSdnVnetsTypeEnum, error) {
	ev := PdmSdnVnetsTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PdmSdnVnetsTypeEnum: valid values are %v", v, AllowedPdmSdnVnetsTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PdmSdnVnetsTypeEnum) IsValid() bool {
	for _, existing := range AllowedPdmSdnVnetsTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PdmSdnVnetsTypeEnum value
func (v PdmSdnVnetsTypeEnum) Ptr() *PdmSdnVnetsTypeEnum {
	return &v
}

type NullablePdmSdnVnetsTypeEnum struct {
	value *PdmSdnVnetsTypeEnum
	isSet bool
}

func (v NullablePdmSdnVnetsTypeEnum) Get() *PdmSdnVnetsTypeEnum {
	return v.value
}

func (v *NullablePdmSdnVnetsTypeEnum) Set(val *PdmSdnVnetsTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmSdnVnetsTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmSdnVnetsTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmSdnVnetsTypeEnum(val *PdmSdnVnetsTypeEnum) *NullablePdmSdnVnetsTypeEnum {
	return &NullablePdmSdnVnetsTypeEnum{value: val, isSet: true}
}

func (v NullablePdmSdnVnetsTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmSdnVnetsTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

