/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesSdnGetIpVrfResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesSdnGetIpVrfResponseData{}

// NodesSdnGetIpVrfResponseData struct for NodesSdnGetIpVrfResponseData
type NodesSdnGetIpVrfResponseData struct {

	// The CIDR of the route table entry.
	Ip string `json:"ip"`

	// This route's metric.
	Metric int64 `json:"metric"`

	// A list of nexthops for the route table entry.
	Nexthops []string `json:"nexthops"`

	// The protocol where this route was learned from (e.g. BGP).
	Protocol string `json:"protocol"`

	AdditionalProperties map[string]interface{}
}

type _NodesSdnGetIpVrfResponseData NodesSdnGetIpVrfResponseData

// NewNodesSdnGetIpVrfResponseData instantiates a new NodesSdnGetIpVrfResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesSdnGetIpVrfResponseData(ip string, metric int64, nexthops []string, protocol string) *NodesSdnGetIpVrfResponseData {
	this := NodesSdnGetIpVrfResponseData{}
	this.Ip = ip
	this.Metric = metric
	this.Nexthops = nexthops
	this.Protocol = protocol
	return &this
}

// NewNodesSdnGetIpVrfResponseDataWithDefaults instantiates a new NodesSdnGetIpVrfResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesSdnGetIpVrfResponseDataWithDefaults() *NodesSdnGetIpVrfResponseData {
	this := NodesSdnGetIpVrfResponseData{}





	return &this
}


// GetIp returns the Ip field value
func (o *NodesSdnGetIpVrfResponseData) GetIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ip
}

// GetIpOk returns a tuple with the Ip field value
// and a boolean to check if the value has been set.
func (o *NodesSdnGetIpVrfResponseData) GetIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ip, true
}

// SetIp sets field value
func (o *NodesSdnGetIpVrfResponseData) SetIp(v string) {
	o.Ip = v
}


// GetMetric returns the Metric field value
func (o *NodesSdnGetIpVrfResponseData) GetMetric() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Metric
}

// GetMetricOk returns a tuple with the Metric field value
// and a boolean to check if the value has been set.
func (o *NodesSdnGetIpVrfResponseData) GetMetricOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metric, true
}

// SetMetric sets field value
func (o *NodesSdnGetIpVrfResponseData) SetMetric(v int64) {
	o.Metric = v
}


// GetNexthops returns the Nexthops field value
func (o *NodesSdnGetIpVrfResponseData) GetNexthops() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Nexthops
}

// GetNexthopsOk returns a tuple with the Nexthops field value
// and a boolean to check if the value has been set.
func (o *NodesSdnGetIpVrfResponseData) GetNexthopsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nexthops, true
}

// SetNexthops sets field value
func (o *NodesSdnGetIpVrfResponseData) SetNexthops(v []string) {
	o.Nexthops = v
}


// GetProtocol returns the Protocol field value
func (o *NodesSdnGetIpVrfResponseData) GetProtocol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *NodesSdnGetIpVrfResponseData) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *NodesSdnGetIpVrfResponseData) SetProtocol(v string) {
	o.Protocol = v
}


func (o NodesSdnGetIpVrfResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesSdnGetIpVrfResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["ip"] = o.Ip
	
	toSerialize["metric"] = o.Metric
	
	toSerialize["nexthops"] = o.Nexthops
	
	toSerialize["protocol"] = o.Protocol
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesSdnGetIpVrfResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ip",
		"metric",
		"nexthops",
		"protocol",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesSdnGetIpVrfResponseData := _NodesSdnGetIpVrfResponseData{}

	err = json.Unmarshal(data, &varNodesSdnGetIpVrfResponseData)

	if err != nil {
		return err
	}

	*o = NodesSdnGetIpVrfResponseData(varNodesSdnGetIpVrfResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ip")
		delete(additionalProperties, "metric")
		delete(additionalProperties, "nexthops")
		delete(additionalProperties, "protocol")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesSdnGetIpVrfResponseData struct {
	value *NodesSdnGetIpVrfResponseData
	isSet bool
}

func (v NullableNodesSdnGetIpVrfResponseData) Get() *NodesSdnGetIpVrfResponseData {
	return v.value
}

func (v *NullableNodesSdnGetIpVrfResponseData) Set(val *NodesSdnGetIpVrfResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesSdnGetIpVrfResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesSdnGetIpVrfResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesSdnGetIpVrfResponseData(val *NodesSdnGetIpVrfResponseData) *NullableNodesSdnGetIpVrfResponseData {
	return &NullableNodesSdnGetIpVrfResponseData{value: val, isSet: true}
}

func (v NullableNodesSdnGetIpVrfResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesSdnGetIpVrfResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


