/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PdmPveRemotesKindEnum the model 'PdmPveRemotesKindEnum'
type PdmPveRemotesKindEnum string

// List of PdmPveRemotesKindEnum
const (
	PDMPVEREMOTESKINDENUM_VM PdmPveRemotesKindEnum = "vm"
	PDMPVEREMOTESKINDENUM_STORAGE PdmPveRemotesKindEnum = "storage"
	PDMPVEREMOTESKINDENUM_NODE PdmPveRemotesKindEnum = "node"
	PDMPVEREMOTESKINDENUM_SDN PdmPveRemotesKindEnum = "sdn"
)

// All allowed values of PdmPveRemotesKindEnum enum
var AllowedPdmPveRemotesKindEnumEnumValues = []PdmPveRemotesKindEnum{
	"vm",
	"storage",
	"node",
	"sdn",
}

func (v *PdmPveRemotesKindEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PdmPveRemotesKindEnum(value)
	for _, existing := range AllowedPdmPveRemotesKindEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PdmPveRemotesKindEnum", value)
}

// NewPdmPveRemotesKindEnumFromValue returns a pointer to a valid PdmPveRemotesKindEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPdmPveRemotesKindEnumFromValue(v string) (*PdmPveRemotesKindEnum, error) {
	ev := PdmPveRemotesKindEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PdmPveRemotesKindEnum: valid values are %v", v, AllowedPdmPveRemotesKindEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PdmPveRemotesKindEnum) IsValid() bool {
	for _, existing := range AllowedPdmPveRemotesKindEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PdmPveRemotesKindEnum value
func (v PdmPveRemotesKindEnum) Ptr() *PdmPveRemotesKindEnum {
	return &v
}

type NullablePdmPveRemotesKindEnum struct {
	value *PdmPveRemotesKindEnum
	isSet bool
}

func (v NullablePdmPveRemotesKindEnum) Get() *PdmPveRemotesKindEnum {
	return v.value
}

func (v *NullablePdmPveRemotesKindEnum) Set(val *PdmPveRemotesKindEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmPveRemotesKindEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmPveRemotesKindEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmPveRemotesKindEnum(val *PdmPveRemotesKindEnum) *NullablePdmPveRemotesKindEnum {
	return &NullablePdmPveRemotesKindEnum{value: val, isSet: true}
}

func (v NullablePdmPveRemotesKindEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmPveRemotesKindEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

