/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigNotesUpdateNotesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigNotesUpdateNotesRequest{}

// ConfigNotesUpdateNotesRequest struct for ConfigNotesUpdateNotesRequest
type ConfigNotesUpdateNotesRequest struct {

	// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty" validate:"regexp=^[a-f0-9]{64}$"`

	// New notes text.
	Notes string `json:"notes"`

}

type _ConfigNotesUpdateNotesRequest ConfigNotesUpdateNotesRequest

// NewConfigNotesUpdateNotesRequest instantiates a new ConfigNotesUpdateNotesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigNotesUpdateNotesRequest(notes string) *ConfigNotesUpdateNotesRequest {
	this := ConfigNotesUpdateNotesRequest{}
	this.Notes = notes
	return &this
}

// NewConfigNotesUpdateNotesRequestWithDefaults instantiates a new ConfigNotesUpdateNotesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigNotesUpdateNotesRequestWithDefaults() *ConfigNotesUpdateNotesRequest {
	this := ConfigNotesUpdateNotesRequest{}



	return &this
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *ConfigNotesUpdateNotesRequest) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigNotesUpdateNotesRequest) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *ConfigNotesUpdateNotesRequest) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *ConfigNotesUpdateNotesRequest) SetDigest(v string) {
	o.Digest = &v
}


// GetNotes returns the Notes field value
func (o *ConfigNotesUpdateNotesRequest) GetNotes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value
// and a boolean to check if the value has been set.
func (o *ConfigNotesUpdateNotesRequest) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Notes, true
}

// SetNotes sets field value
func (o *ConfigNotesUpdateNotesRequest) SetNotes(v string) {
	o.Notes = v
}


func (o ConfigNotesUpdateNotesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigNotesUpdateNotesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	toSerialize["notes"] = o.Notes
	
	return toSerialize, nil
}

func (o *ConfigNotesUpdateNotesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"notes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigNotesUpdateNotesRequest := _ConfigNotesUpdateNotesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigNotesUpdateNotesRequest)

	if err != nil {
		return err
	}

	*o = ConfigNotesUpdateNotesRequest(varConfigNotesUpdateNotesRequest)

	return err
}

type NullableConfigNotesUpdateNotesRequest struct {
	value *ConfigNotesUpdateNotesRequest
	isSet bool
}

func (v NullableConfigNotesUpdateNotesRequest) Get() *ConfigNotesUpdateNotesRequest {
	return v.value
}

func (v *NullableConfigNotesUpdateNotesRequest) Set(val *ConfigNotesUpdateNotesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigNotesUpdateNotesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigNotesUpdateNotesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigNotesUpdateNotesRequest(val *ConfigNotesUpdateNotesRequest) *NullableConfigNotesUpdateNotesRequest {
	return &NullableConfigNotesUpdateNotesRequest{value: val, isSet: true}
}

func (v NullableConfigNotesUpdateNotesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigNotesUpdateNotesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


