/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesAptGetRepositoriesResponseDataInfosInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesAptGetRepositoriesResponseDataInfosInner{}

// NodesAptGetRepositoriesResponseDataInfosInner struct for NodesAptGetRepositoriesResponseDataInfosInner
type NodesAptGetRepositoriesResponseDataInfosInner struct {

	// Index of the associated repository within the file (starting from 0).
	Index int64 `json:"index"`

	// Info kind (e.g. \"warning\")
	Kind string `json:"kind"`

	// Info message
	Message string `json:"message"`

	// Path to the defining file.
	Path string `json:"path"`

	// The property from which the info originates (e.g. \"Suites\")
	Property *string `json:"property,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _NodesAptGetRepositoriesResponseDataInfosInner NodesAptGetRepositoriesResponseDataInfosInner

// NewNodesAptGetRepositoriesResponseDataInfosInner instantiates a new NodesAptGetRepositoriesResponseDataInfosInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesAptGetRepositoriesResponseDataInfosInner(index int64, kind string, message string, path string) *NodesAptGetRepositoriesResponseDataInfosInner {
	this := NodesAptGetRepositoriesResponseDataInfosInner{}
	this.Index = index
	this.Kind = kind
	this.Message = message
	this.Path = path
	return &this
}

// NewNodesAptGetRepositoriesResponseDataInfosInnerWithDefaults instantiates a new NodesAptGetRepositoriesResponseDataInfosInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesAptGetRepositoriesResponseDataInfosInnerWithDefaults() *NodesAptGetRepositoriesResponseDataInfosInner {
	this := NodesAptGetRepositoriesResponseDataInfosInner{}






	return &this
}


// GetIndex returns the Index field value
func (o *NodesAptGetRepositoriesResponseDataInfosInner) GetIndex() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataInfosInner) GetIndexOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *NodesAptGetRepositoriesResponseDataInfosInner) SetIndex(v int64) {
	o.Index = v
}


// GetKind returns the Kind field value
func (o *NodesAptGetRepositoriesResponseDataInfosInner) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataInfosInner) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *NodesAptGetRepositoriesResponseDataInfosInner) SetKind(v string) {
	o.Kind = v
}


// GetMessage returns the Message field value
func (o *NodesAptGetRepositoriesResponseDataInfosInner) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataInfosInner) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *NodesAptGetRepositoriesResponseDataInfosInner) SetMessage(v string) {
	o.Message = v
}


// GetPath returns the Path field value
func (o *NodesAptGetRepositoriesResponseDataInfosInner) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataInfosInner) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *NodesAptGetRepositoriesResponseDataInfosInner) SetPath(v string) {
	o.Path = v
}


// GetProperty returns the Property field value if set, zero value otherwise.
func (o *NodesAptGetRepositoriesResponseDataInfosInner) GetProperty() string {
	if o == nil || IsNil(o.Property) {
		var ret string
		return ret
	}
	return *o.Property
}

// GetPropertyOk returns a tuple with the Property field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataInfosInner) GetPropertyOk() (*string, bool) {
	if o == nil || IsNil(o.Property) {
		return nil, false
	}
	return o.Property, true
}

// HasProperty returns a boolean if a field has been set.
func (o *NodesAptGetRepositoriesResponseDataInfosInner) HasProperty() bool {
	if o != nil && !IsNil(o.Property) {
		return true
	}

	return false
}

// SetProperty gets a reference to the given string and assigns it to the Property field.
func (o *NodesAptGetRepositoriesResponseDataInfosInner) SetProperty(v string) {
	o.Property = &v
}


func (o NodesAptGetRepositoriesResponseDataInfosInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesAptGetRepositoriesResponseDataInfosInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["index"] = o.Index
	
	toSerialize["kind"] = o.Kind
	
	toSerialize["message"] = o.Message
	
	toSerialize["path"] = o.Path
	
	if !IsNil(o.Property) {
		toSerialize["property"] = o.Property
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesAptGetRepositoriesResponseDataInfosInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index",
		"kind",
		"message",
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesAptGetRepositoriesResponseDataInfosInner := _NodesAptGetRepositoriesResponseDataInfosInner{}

	err = json.Unmarshal(data, &varNodesAptGetRepositoriesResponseDataInfosInner)

	if err != nil {
		return err
	}

	*o = NodesAptGetRepositoriesResponseDataInfosInner(varNodesAptGetRepositoriesResponseDataInfosInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "index")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "message")
		delete(additionalProperties, "path")
		delete(additionalProperties, "property")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesAptGetRepositoriesResponseDataInfosInner struct {
	value *NodesAptGetRepositoriesResponseDataInfosInner
	isSet bool
}

func (v NullableNodesAptGetRepositoriesResponseDataInfosInner) Get() *NodesAptGetRepositoriesResponseDataInfosInner {
	return v.value
}

func (v *NullableNodesAptGetRepositoriesResponseDataInfosInner) Set(val *NodesAptGetRepositoriesResponseDataInfosInner) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesAptGetRepositoriesResponseDataInfosInner) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesAptGetRepositoriesResponseDataInfosInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesAptGetRepositoriesResponseDataInfosInner(val *NodesAptGetRepositoriesResponseDataInfosInner) *NullableNodesAptGetRepositoriesResponseDataInfosInner {
	return &NullableNodesAptGetRepositoriesResponseDataInfosInner{value: val, isSet: true}
}

func (v NullableNodesAptGetRepositoriesResponseDataInfosInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesAptGetRepositoriesResponseDataInfosInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


