/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesStatusGetStatusResponseDataCpuinfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesStatusGetStatusResponseDataCpuinfo{}

// NodesStatusGetStatusResponseDataCpuinfo Information about the CPU
type NodesStatusGetStatusResponseDataCpuinfo struct {

	// The number of CPU cores (incl. threads)
	Cpus int64 `json:"cpus"`

	// The CPU model
	Model string `json:"model"`

	// The number of CPU sockets
	Sockets int64 `json:"sockets"`

	AdditionalProperties map[string]interface{}
}

type _NodesStatusGetStatusResponseDataCpuinfo NodesStatusGetStatusResponseDataCpuinfo

// NewNodesStatusGetStatusResponseDataCpuinfo instantiates a new NodesStatusGetStatusResponseDataCpuinfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesStatusGetStatusResponseDataCpuinfo(cpus int64, model string, sockets int64) *NodesStatusGetStatusResponseDataCpuinfo {
	this := NodesStatusGetStatusResponseDataCpuinfo{}
	this.Cpus = cpus
	this.Model = model
	this.Sockets = sockets
	return &this
}

// NewNodesStatusGetStatusResponseDataCpuinfoWithDefaults instantiates a new NodesStatusGetStatusResponseDataCpuinfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesStatusGetStatusResponseDataCpuinfoWithDefaults() *NodesStatusGetStatusResponseDataCpuinfo {
	this := NodesStatusGetStatusResponseDataCpuinfo{}




	return &this
}


// GetCpus returns the Cpus field value
func (o *NodesStatusGetStatusResponseDataCpuinfo) GetCpus() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Cpus
}

// GetCpusOk returns a tuple with the Cpus field value
// and a boolean to check if the value has been set.
func (o *NodesStatusGetStatusResponseDataCpuinfo) GetCpusOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpus, true
}

// SetCpus sets field value
func (o *NodesStatusGetStatusResponseDataCpuinfo) SetCpus(v int64) {
	o.Cpus = v
}


// GetModel returns the Model field value
func (o *NodesStatusGetStatusResponseDataCpuinfo) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *NodesStatusGetStatusResponseDataCpuinfo) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *NodesStatusGetStatusResponseDataCpuinfo) SetModel(v string) {
	o.Model = v
}


// GetSockets returns the Sockets field value
func (o *NodesStatusGetStatusResponseDataCpuinfo) GetSockets() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Sockets
}

// GetSocketsOk returns a tuple with the Sockets field value
// and a boolean to check if the value has been set.
func (o *NodesStatusGetStatusResponseDataCpuinfo) GetSocketsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sockets, true
}

// SetSockets sets field value
func (o *NodesStatusGetStatusResponseDataCpuinfo) SetSockets(v int64) {
	o.Sockets = v
}


func (o NodesStatusGetStatusResponseDataCpuinfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesStatusGetStatusResponseDataCpuinfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["cpus"] = o.Cpus
	
	toSerialize["model"] = o.Model
	
	toSerialize["sockets"] = o.Sockets
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesStatusGetStatusResponseDataCpuinfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cpus",
		"model",
		"sockets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesStatusGetStatusResponseDataCpuinfo := _NodesStatusGetStatusResponseDataCpuinfo{}

	err = json.Unmarshal(data, &varNodesStatusGetStatusResponseDataCpuinfo)

	if err != nil {
		return err
	}

	*o = NodesStatusGetStatusResponseDataCpuinfo(varNodesStatusGetStatusResponseDataCpuinfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cpus")
		delete(additionalProperties, "model")
		delete(additionalProperties, "sockets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesStatusGetStatusResponseDataCpuinfo struct {
	value *NodesStatusGetStatusResponseDataCpuinfo
	isSet bool
}

func (v NullableNodesStatusGetStatusResponseDataCpuinfo) Get() *NodesStatusGetStatusResponseDataCpuinfo {
	return v.value
}

func (v *NullableNodesStatusGetStatusResponseDataCpuinfo) Set(val *NodesStatusGetStatusResponseDataCpuinfo) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesStatusGetStatusResponseDataCpuinfo) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesStatusGetStatusResponseDataCpuinfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesStatusGetStatusResponseDataCpuinfo(val *NodesStatusGetStatusResponseDataCpuinfo) *NullableNodesStatusGetStatusResponseDataCpuinfo {
	return &NullableNodesStatusGetStatusResponseDataCpuinfo{value: val, isSet: true}
}

func (v NullableNodesStatusGetStatusResponseDataCpuinfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesStatusGetStatusResponseDataCpuinfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


