/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesAptGetRepositoriesResponseDataStandardReposInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesAptGetRepositoriesResponseDataStandardReposInner{}

// NodesAptGetRepositoriesResponseDataStandardReposInner struct for NodesAptGetRepositoriesResponseDataStandardReposInner
type NodesAptGetRepositoriesResponseDataStandardReposInner struct {

	// Description of the repository.
	Description string `json:"description"`

	// Handle referencing a standard repository.
	Handle string `json:"handle"`

	// Display name of the repository.
	Name string `json:"name"`

	// Configuration status of the associated repository, where `None` means not configured, and `Some(bool)` indicates enabled or disabled.
	Status *bool `json:"status,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _NodesAptGetRepositoriesResponseDataStandardReposInner NodesAptGetRepositoriesResponseDataStandardReposInner

// NewNodesAptGetRepositoriesResponseDataStandardReposInner instantiates a new NodesAptGetRepositoriesResponseDataStandardReposInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesAptGetRepositoriesResponseDataStandardReposInner(description string, handle string, name string) *NodesAptGetRepositoriesResponseDataStandardReposInner {
	this := NodesAptGetRepositoriesResponseDataStandardReposInner{}
	this.Description = description
	this.Handle = handle
	this.Name = name
	return &this
}

// NewNodesAptGetRepositoriesResponseDataStandardReposInnerWithDefaults instantiates a new NodesAptGetRepositoriesResponseDataStandardReposInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesAptGetRepositoriesResponseDataStandardReposInnerWithDefaults() *NodesAptGetRepositoriesResponseDataStandardReposInner {
	this := NodesAptGetRepositoriesResponseDataStandardReposInner{}





	return &this
}


// GetDescription returns the Description field value
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) SetDescription(v string) {
	o.Description = v
}


// GetHandle returns the Handle field value
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) GetHandle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Handle
}

// GetHandleOk returns a tuple with the Handle field value
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) GetHandleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Handle, true
}

// SetHandle sets field value
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) SetHandle(v string) {
	o.Handle = v
}


// GetName returns the Name field value
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) SetName(v string) {
	o.Name = v
}


// GetStatus returns the Status field value if set, zero value otherwise.
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) SetStatus(v bool) {
	o.Status = &v
}


func (o NodesAptGetRepositoriesResponseDataStandardReposInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesAptGetRepositoriesResponseDataStandardReposInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["description"] = o.Description
	
	toSerialize["handle"] = o.Handle
	
	toSerialize["name"] = o.Name
	
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesAptGetRepositoriesResponseDataStandardReposInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"handle",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesAptGetRepositoriesResponseDataStandardReposInner := _NodesAptGetRepositoriesResponseDataStandardReposInner{}

	err = json.Unmarshal(data, &varNodesAptGetRepositoriesResponseDataStandardReposInner)

	if err != nil {
		return err
	}

	*o = NodesAptGetRepositoriesResponseDataStandardReposInner(varNodesAptGetRepositoriesResponseDataStandardReposInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "handle")
		delete(additionalProperties, "name")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesAptGetRepositoriesResponseDataStandardReposInner struct {
	value *NodesAptGetRepositoriesResponseDataStandardReposInner
	isSet bool
}

func (v NullableNodesAptGetRepositoriesResponseDataStandardReposInner) Get() *NodesAptGetRepositoriesResponseDataStandardReposInner {
	return v.value
}

func (v *NullableNodesAptGetRepositoriesResponseDataStandardReposInner) Set(val *NodesAptGetRepositoriesResponseDataStandardReposInner) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesAptGetRepositoriesResponseDataStandardReposInner) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesAptGetRepositoriesResponseDataStandardReposInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesAptGetRepositoriesResponseDataStandardReposInner(val *NodesAptGetRepositoriesResponseDataStandardReposInner) *NullableNodesAptGetRepositoriesResponseDataStandardReposInner {
	return &NullableNodesAptGetRepositoriesResponseDataStandardReposInner{value: val, isSet: true}
}

func (v NullableNodesAptGetRepositoriesResponseDataStandardReposInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesAptGetRepositoriesResponseDataStandardReposInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


