/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount{}

// ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount ACME Account data. This is the part of the account returned from and possibly sent to the ACME provider. Some fields may be uptdated by the user via a request to the account location, others may not be changed.
type ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount struct {

	// The account's contact info.  This usually contains a `\"mailto:<email address>\"` entry but may also contain some other data if the server accepts it.
	Contact []string `json:"contact"`

	ExternalAccountBinding *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccountExternalAccountBinding `json:"externalAccountBinding,omitempty"`

	// This is only used by the client when querying an account.
	OnlyReturnExisting bool `json:"onlyReturnExisting"`

	// URLs to currently pending orders.
	Orders *string `json:"orders,omitempty"`

	// Status of an ACME account.
	Status PdmConfigAcmeStatusEnum `json:"status"`

	// Indicated whether the user agreed to the ACME provider's terms of service.
	TermsOfServiceAgreed *bool `json:"termsOfServiceAgreed,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount

// NewConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount instantiates a new ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount(contact []string, onlyReturnExisting bool, status PdmConfigAcmeStatusEnum) *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount {
	this := ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount{}
	this.Contact = contact
	this.OnlyReturnExisting = onlyReturnExisting
	this.Status = status
	return &this
}

// NewConfigAcmeGetConfigAcmeAccountByNameResponseDataAccountWithDefaults instantiates a new ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigAcmeGetConfigAcmeAccountByNameResponseDataAccountWithDefaults() *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount {
	this := ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount{}







	return &this
}


// GetContact returns the Contact field value
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) GetContact() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Contact
}

// GetContactOk returns a tuple with the Contact field value
// and a boolean to check if the value has been set.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) GetContactOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Contact, true
}

// SetContact sets field value
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) SetContact(v []string) {
	o.Contact = v
}


// GetExternalAccountBinding returns the ExternalAccountBinding field value if set, zero value otherwise.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) GetExternalAccountBinding() ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccountExternalAccountBinding {
	if o == nil || IsNil(o.ExternalAccountBinding) {
		var ret ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccountExternalAccountBinding
		return ret
	}
	return *o.ExternalAccountBinding
}

// GetExternalAccountBindingOk returns a tuple with the ExternalAccountBinding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) GetExternalAccountBindingOk() (*ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccountExternalAccountBinding, bool) {
	if o == nil || IsNil(o.ExternalAccountBinding) {
		return nil, false
	}
	return o.ExternalAccountBinding, true
}

// HasExternalAccountBinding returns a boolean if a field has been set.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) HasExternalAccountBinding() bool {
	if o != nil && !IsNil(o.ExternalAccountBinding) {
		return true
	}

	return false
}

// SetExternalAccountBinding gets a reference to the given ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccountExternalAccountBinding and assigns it to the ExternalAccountBinding field.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) SetExternalAccountBinding(v ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccountExternalAccountBinding) {
	o.ExternalAccountBinding = &v
}


// GetOnlyReturnExisting returns the OnlyReturnExisting field value
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) GetOnlyReturnExisting() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OnlyReturnExisting
}

// GetOnlyReturnExistingOk returns a tuple with the OnlyReturnExisting field value
// and a boolean to check if the value has been set.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) GetOnlyReturnExistingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OnlyReturnExisting, true
}

// SetOnlyReturnExisting sets field value
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) SetOnlyReturnExisting(v bool) {
	o.OnlyReturnExisting = v
}


// GetOrders returns the Orders field value if set, zero value otherwise.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) GetOrders() string {
	if o == nil || IsNil(o.Orders) {
		var ret string
		return ret
	}
	return *o.Orders
}

// GetOrdersOk returns a tuple with the Orders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) GetOrdersOk() (*string, bool) {
	if o == nil || IsNil(o.Orders) {
		return nil, false
	}
	return o.Orders, true
}

// HasOrders returns a boolean if a field has been set.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) HasOrders() bool {
	if o != nil && !IsNil(o.Orders) {
		return true
	}

	return false
}

// SetOrders gets a reference to the given string and assigns it to the Orders field.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) SetOrders(v string) {
	o.Orders = &v
}


// GetStatus returns the Status field value
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) GetStatus() PdmConfigAcmeStatusEnum {
	if o == nil {
		var ret PdmConfigAcmeStatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) GetStatusOk() (*PdmConfigAcmeStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) SetStatus(v PdmConfigAcmeStatusEnum) {
	o.Status = v
}


// GetTermsOfServiceAgreed returns the TermsOfServiceAgreed field value if set, zero value otherwise.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) GetTermsOfServiceAgreed() bool {
	if o == nil || IsNil(o.TermsOfServiceAgreed) {
		var ret bool
		return ret
	}
	return *o.TermsOfServiceAgreed
}

// GetTermsOfServiceAgreedOk returns a tuple with the TermsOfServiceAgreed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) GetTermsOfServiceAgreedOk() (*bool, bool) {
	if o == nil || IsNil(o.TermsOfServiceAgreed) {
		return nil, false
	}
	return o.TermsOfServiceAgreed, true
}

// HasTermsOfServiceAgreed returns a boolean if a field has been set.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) HasTermsOfServiceAgreed() bool {
	if o != nil && !IsNil(o.TermsOfServiceAgreed) {
		return true
	}

	return false
}

// SetTermsOfServiceAgreed gets a reference to the given bool and assigns it to the TermsOfServiceAgreed field.
func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) SetTermsOfServiceAgreed(v bool) {
	o.TermsOfServiceAgreed = &v
}


func (o ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["contact"] = o.Contact
	
	if !IsNil(o.ExternalAccountBinding) {
		toSerialize["externalAccountBinding"] = o.ExternalAccountBinding
	}
	
	toSerialize["onlyReturnExisting"] = o.OnlyReturnExisting
	
	if !IsNil(o.Orders) {
		toSerialize["orders"] = o.Orders
	}
	
	toSerialize["status"] = o.Status
	
	if !IsNil(o.TermsOfServiceAgreed) {
		toSerialize["termsOfServiceAgreed"] = o.TermsOfServiceAgreed
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"contact",
		"onlyReturnExisting",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount := _ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount{}

	err = json.Unmarshal(data, &varConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount)

	if err != nil {
		return err
	}

	*o = ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount(varConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "contact")
		delete(additionalProperties, "externalAccountBinding")
		delete(additionalProperties, "onlyReturnExisting")
		delete(additionalProperties, "orders")
		delete(additionalProperties, "status")
		delete(additionalProperties, "termsOfServiceAgreed")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount struct {
	value *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount
	isSet bool
}

func (v NullableConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) Get() *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount {
	return v.value
}

func (v *NullableConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) Set(val *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount(val *ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) *NullableConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount {
	return &NullableConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount{value: val, isSet: true}
}

func (v NullableConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


