/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PdmUnusedField - struct for PdmUnusedField
type PdmUnusedField struct {
	PdmLogRatelimitConfig *PdmLogRatelimitConfig
	String *string
}

// PdmLogRatelimitConfigAsPdmUnusedField is a convenience function that returns PdmLogRatelimitConfig wrapped in PdmUnusedField
func PdmLogRatelimitConfigAsPdmUnusedField(v *PdmLogRatelimitConfig) PdmUnusedField {
	return PdmUnusedField{
		PdmLogRatelimitConfig: v,
	}
}

// stringAsPdmUnusedField is a convenience function that returns string wrapped in PdmUnusedField
func StringAsPdmUnusedField(v *string) PdmUnusedField {
	return PdmUnusedField{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PdmUnusedField) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PdmLogRatelimitConfig
	err = newStrictDecoder(data).Decode(&dst.PdmLogRatelimitConfig)
	if err == nil {
		jsonPdmLogRatelimitConfig, _ := json.Marshal(dst.PdmLogRatelimitConfig)
		if string(jsonPdmLogRatelimitConfig) == "{}" { // empty struct
			dst.PdmLogRatelimitConfig = nil
		} else {
			if err = validator.Validate(dst.PdmLogRatelimitConfig); err != nil {
				dst.PdmLogRatelimitConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.PdmLogRatelimitConfig = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PdmLogRatelimitConfig = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PdmUnusedField)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PdmUnusedField)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PdmUnusedField) MarshalJSON() ([]byte, error) {
	if src.PdmLogRatelimitConfig != nil {
		return json.Marshal(&src.PdmLogRatelimitConfig)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PdmUnusedField) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PdmLogRatelimitConfig != nil {
		return obj.PdmLogRatelimitConfig
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PdmUnusedField) GetActualInstanceValue() (interface{}) {
	if obj.PdmLogRatelimitConfig != nil {
		return *obj.PdmLogRatelimitConfig
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePdmUnusedField struct {
	value *PdmUnusedField
	isSet bool
}

func (v NullablePdmUnusedField) Get() *PdmUnusedField {
	return v.value
}

func (v *NullablePdmUnusedField) Set(val *PdmUnusedField) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmUnusedField) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmUnusedField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmUnusedField(val *PdmUnusedField) *NullablePdmUnusedField {
	return &NullablePdmUnusedField{value: val, isSet: true}
}

func (v NullablePdmUnusedField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmUnusedField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


