/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PdmStatusEnum the model 'PdmStatusEnum'
type PdmStatusEnum string

// List of PdmStatusEnum
const (
	PDMSTATUSENUM_NEW PdmStatusEnum = "new"
	PDMSTATUSENUM_NOTFOUND PdmStatusEnum = "notfound"
	PDMSTATUSENUM_ACTIVE PdmStatusEnum = "active"
	PDMSTATUSENUM_INVALID PdmStatusEnum = "invalid"
	PDMSTATUSENUM_EXPIRED PdmStatusEnum = "expired"
	PDMSTATUSENUM_SUSPENDED PdmStatusEnum = "suspended"
)

// All allowed values of PdmStatusEnum enum
var AllowedPdmStatusEnumEnumValues = []PdmStatusEnum{
	"new",
	"notfound",
	"active",
	"invalid",
	"expired",
	"suspended",
}

func (v *PdmStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PdmStatusEnum(value)
	for _, existing := range AllowedPdmStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PdmStatusEnum", value)
}

// NewPdmStatusEnumFromValue returns a pointer to a valid PdmStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPdmStatusEnumFromValue(v string) (*PdmStatusEnum, error) {
	ev := PdmStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PdmStatusEnum: valid values are %v", v, AllowedPdmStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PdmStatusEnum) IsValid() bool {
	for _, existing := range AllowedPdmStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PdmStatusEnum value
func (v PdmStatusEnum) Ptr() *PdmStatusEnum {
	return &v
}

type NullablePdmStatusEnum struct {
	value *PdmStatusEnum
	isSet bool
}

func (v NullablePdmStatusEnum) Get() *PdmStatusEnum {
	return v.value
}

func (v *NullablePdmStatusEnum) Set(val *PdmStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmStatusEnum(val *PdmStatusEnum) *NullablePdmStatusEnum {
	return &NullablePdmStatusEnum{value: val, isSet: true}
}

func (v NullablePdmStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

