/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PdmContentConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PdmContentConfig{}

// PdmContentConfig struct for PdmContentConfig
type PdmContentConfig struct {

	Description interface{} `json:"description"`

	// Storage content type.
	Items PdmPveRemotesItemsEnum `json:"items"`

	Type interface{} `json:"type"`

}

type _PdmContentConfig PdmContentConfig

// NewPdmContentConfig instantiates a new PdmContentConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPdmContentConfig(description interface{}, items PdmPveRemotesItemsEnum, type_ interface{}) *PdmContentConfig {
	this := PdmContentConfig{}
	this.Description = description
	this.Items = items
	this.Type = type_
	return &this
}

// NewPdmContentConfigWithDefaults instantiates a new PdmContentConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPdmContentConfigWithDefaults() *PdmContentConfig {
	this := PdmContentConfig{}




	return &this
}


// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PdmContentConfig) GetDescription() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PdmContentConfig) GetDescriptionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PdmContentConfig) SetDescription(v interface{}) {
	o.Description = v
}


// GetItems returns the Items field value
func (o *PdmContentConfig) GetItems() PdmPveRemotesItemsEnum {
	if o == nil {
		var ret PdmPveRemotesItemsEnum
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PdmContentConfig) GetItemsOk() (*PdmPveRemotesItemsEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *PdmContentConfig) SetItems(v PdmPveRemotesItemsEnum) {
	o.Items = v
}


// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PdmContentConfig) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PdmContentConfig) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PdmContentConfig) SetType(v interface{}) {
	o.Type = v
}


func (o PdmContentConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PdmContentConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	
	toSerialize["items"] = o.Items
	
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	
	return toSerialize, nil
}

func (o *PdmContentConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"items",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPdmContentConfig := _PdmContentConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPdmContentConfig)

	if err != nil {
		return err
	}

	*o = PdmContentConfig(varPdmContentConfig)

	return err
}

type NullablePdmContentConfig struct {
	value *PdmContentConfig
	isSet bool
}

func (v NullablePdmContentConfig) Get() *PdmContentConfig {
	return v.value
}

func (v *NullablePdmContentConfig) Set(val *PdmContentConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmContentConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmContentConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmContentConfig(val *PdmContentConfig) *NullablePdmContentConfig {
	return &NullablePdmContentConfig{value: val, isSet: true}
}

func (v NullablePdmContentConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmContentConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


