/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AccessUsersUpdateTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessUsersUpdateTokenRequest{}

// AccessUsersUpdateTokenRequest struct for AccessUsersUpdateTokenRequest
type AccessUsersUpdateTokenRequest struct {

	// Comment.
	Comment *string `json:"comment,omitempty" validate:"regexp=^[[:^cntrl:]]*$"`

	// List of properties to delete.
	Delete []PdmAccessUsersInlineEnum2 `json:"delete,omitempty"`

	// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty" validate:"regexp=^[a-f0-9]{64}$"`

	// Enable the account (default). You can set this to '0' to disable the account.
	Enable *bool `json:"enable,omitempty"`

	// Account expiration date (seconds since epoch). '0' means no expiration date.
	Expire *int64 `json:"expire,omitempty"`

	// Regenerate token secret while keeping permissions.
	Regenerate *bool `json:"regenerate,omitempty"`

}

// NewAccessUsersUpdateTokenRequest instantiates a new AccessUsersUpdateTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessUsersUpdateTokenRequest() *AccessUsersUpdateTokenRequest {
	this := AccessUsersUpdateTokenRequest{}
	var enable bool = true
	this.Enable = &enable
	var expire int64 = 0
	this.Expire = &expire
	var regenerate bool = false
	this.Regenerate = &regenerate
	return &this
}

// NewAccessUsersUpdateTokenRequestWithDefaults instantiates a new AccessUsersUpdateTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessUsersUpdateTokenRequestWithDefaults() *AccessUsersUpdateTokenRequest {
	this := AccessUsersUpdateTokenRequest{}




	var enable bool = true
	this.Enable = &enable

	var expire int64 = 0
	this.Expire = &expire

	var regenerate bool = false
	this.Regenerate = &regenerate

	return &this
}


// GetComment returns the Comment field value if set, zero value otherwise.
func (o *AccessUsersUpdateTokenRequest) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersUpdateTokenRequest) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *AccessUsersUpdateTokenRequest) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *AccessUsersUpdateTokenRequest) SetComment(v string) {
	o.Comment = &v
}


// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *AccessUsersUpdateTokenRequest) GetDelete() []PdmAccessUsersInlineEnum2 {
	if o == nil || IsNil(o.Delete) {
		var ret []PdmAccessUsersInlineEnum2
		return ret
	}
	return o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersUpdateTokenRequest) GetDeleteOk() ([]PdmAccessUsersInlineEnum2, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *AccessUsersUpdateTokenRequest) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given []PdmAccessUsersInlineEnum2 and assigns it to the Delete field.
func (o *AccessUsersUpdateTokenRequest) SetDelete(v []PdmAccessUsersInlineEnum2) {
	o.Delete = v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *AccessUsersUpdateTokenRequest) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersUpdateTokenRequest) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *AccessUsersUpdateTokenRequest) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *AccessUsersUpdateTokenRequest) SetDigest(v string) {
	o.Digest = &v
}


// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *AccessUsersUpdateTokenRequest) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersUpdateTokenRequest) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *AccessUsersUpdateTokenRequest) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *AccessUsersUpdateTokenRequest) SetEnable(v bool) {
	o.Enable = &v
}


// GetExpire returns the Expire field value if set, zero value otherwise.
func (o *AccessUsersUpdateTokenRequest) GetExpire() int64 {
	if o == nil || IsNil(o.Expire) {
		var ret int64
		return ret
	}
	return *o.Expire
}

// GetExpireOk returns a tuple with the Expire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersUpdateTokenRequest) GetExpireOk() (*int64, bool) {
	if o == nil || IsNil(o.Expire) {
		return nil, false
	}
	return o.Expire, true
}

// HasExpire returns a boolean if a field has been set.
func (o *AccessUsersUpdateTokenRequest) HasExpire() bool {
	if o != nil && !IsNil(o.Expire) {
		return true
	}

	return false
}

// SetExpire gets a reference to the given int64 and assigns it to the Expire field.
func (o *AccessUsersUpdateTokenRequest) SetExpire(v int64) {
	o.Expire = &v
}


// GetRegenerate returns the Regenerate field value if set, zero value otherwise.
func (o *AccessUsersUpdateTokenRequest) GetRegenerate() bool {
	if o == nil || IsNil(o.Regenerate) {
		var ret bool
		return ret
	}
	return *o.Regenerate
}

// GetRegenerateOk returns a tuple with the Regenerate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersUpdateTokenRequest) GetRegenerateOk() (*bool, bool) {
	if o == nil || IsNil(o.Regenerate) {
		return nil, false
	}
	return o.Regenerate, true
}

// HasRegenerate returns a boolean if a field has been set.
func (o *AccessUsersUpdateTokenRequest) HasRegenerate() bool {
	if o != nil && !IsNil(o.Regenerate) {
		return true
	}

	return false
}

// SetRegenerate gets a reference to the given bool and assigns it to the Regenerate field.
func (o *AccessUsersUpdateTokenRequest) SetRegenerate(v bool) {
	o.Regenerate = &v
}


func (o AccessUsersUpdateTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessUsersUpdateTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	
	if !IsNil(o.Expire) {
		toSerialize["expire"] = o.Expire
	}
	
	if !IsNil(o.Regenerate) {
		toSerialize["regenerate"] = o.Regenerate
	}
	
	return toSerialize, nil
}

type NullableAccessUsersUpdateTokenRequest struct {
	value *AccessUsersUpdateTokenRequest
	isSet bool
}

func (v NullableAccessUsersUpdateTokenRequest) Get() *AccessUsersUpdateTokenRequest {
	return v.value
}

func (v *NullableAccessUsersUpdateTokenRequest) Set(val *AccessUsersUpdateTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessUsersUpdateTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessUsersUpdateTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessUsersUpdateTokenRequest(val *AccessUsersUpdateTokenRequest) *NullableAccessUsersUpdateTokenRequest {
	return &NullableAccessUsersUpdateTokenRequest{value: val, isSet: true}
}

func (v NullableAccessUsersUpdateTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessUsersUpdateTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


