/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PdmPveRemotesArchEnum the model 'PdmPveRemotesArchEnum'
type PdmPveRemotesArchEnum string

// List of PdmPveRemotesArchEnum
const (
	PDMPVEREMOTESARCHENUM_AMD64 PdmPveRemotesArchEnum = "amd64"
	PDMPVEREMOTESARCHENUM_I386 PdmPveRemotesArchEnum = "i386"
	PDMPVEREMOTESARCHENUM_ARM64 PdmPveRemotesArchEnum = "arm64"
	PDMPVEREMOTESARCHENUM_ARMHF PdmPveRemotesArchEnum = "armhf"
	PDMPVEREMOTESARCHENUM_RISCV32 PdmPveRemotesArchEnum = "riscv32"
	PDMPVEREMOTESARCHENUM_RISCV64 PdmPveRemotesArchEnum = "riscv64"
)

// All allowed values of PdmPveRemotesArchEnum enum
var AllowedPdmPveRemotesArchEnumEnumValues = []PdmPveRemotesArchEnum{
	"amd64",
	"i386",
	"arm64",
	"armhf",
	"riscv32",
	"riscv64",
}

func (v *PdmPveRemotesArchEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PdmPveRemotesArchEnum(value)
	for _, existing := range AllowedPdmPveRemotesArchEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PdmPveRemotesArchEnum", value)
}

// NewPdmPveRemotesArchEnumFromValue returns a pointer to a valid PdmPveRemotesArchEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPdmPveRemotesArchEnumFromValue(v string) (*PdmPveRemotesArchEnum, error) {
	ev := PdmPveRemotesArchEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PdmPveRemotesArchEnum: valid values are %v", v, AllowedPdmPveRemotesArchEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PdmPveRemotesArchEnum) IsValid() bool {
	for _, existing := range AllowedPdmPveRemotesArchEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PdmPveRemotesArchEnum value
func (v PdmPveRemotesArchEnum) Ptr() *PdmPveRemotesArchEnum {
	return &v
}

type NullablePdmPveRemotesArchEnum struct {
	value *PdmPveRemotesArchEnum
	isSet bool
}

func (v NullablePdmPveRemotesArchEnum) Get() *PdmPveRemotesArchEnum {
	return v.value
}

func (v *NullablePdmPveRemotesArchEnum) Set(val *PdmPveRemotesArchEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmPveRemotesArchEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmPveRemotesArchEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmPveRemotesArchEnum(val *PdmPveRemotesArchEnum) *NullablePdmPveRemotesArchEnum {
	return &NullablePdmPveRemotesArchEnum{value: val, isSet: true}
}

func (v NullablePdmPveRemotesArchEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmPveRemotesArchEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

