/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NodesTimeUpdateTimeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesTimeUpdateTimeRequest{}

// NodesTimeUpdateTimeRequest struct for NodesTimeUpdateTimeRequest
type NodesTimeUpdateTimeRequest struct {

	// Time zone. The file '/usr/share/zoneinfo/zone.tab' contains the list of valid names.
	Timezone string `json:"timezone" validate:"regexp=^[[:^cntrl:]]*$"`

}

type _NodesTimeUpdateTimeRequest NodesTimeUpdateTimeRequest

// NewNodesTimeUpdateTimeRequest instantiates a new NodesTimeUpdateTimeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesTimeUpdateTimeRequest(timezone string) *NodesTimeUpdateTimeRequest {
	this := NodesTimeUpdateTimeRequest{}
	this.Timezone = timezone
	return &this
}

// NewNodesTimeUpdateTimeRequestWithDefaults instantiates a new NodesTimeUpdateTimeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesTimeUpdateTimeRequestWithDefaults() *NodesTimeUpdateTimeRequest {
	this := NodesTimeUpdateTimeRequest{}


	return &this
}


// GetTimezone returns the Timezone field value
func (o *NodesTimeUpdateTimeRequest) GetTimezone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value
// and a boolean to check if the value has been set.
func (o *NodesTimeUpdateTimeRequest) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timezone, true
}

// SetTimezone sets field value
func (o *NodesTimeUpdateTimeRequest) SetTimezone(v string) {
	o.Timezone = v
}


func (o NodesTimeUpdateTimeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesTimeUpdateTimeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["timezone"] = o.Timezone
	
	return toSerialize, nil
}

func (o *NodesTimeUpdateTimeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timezone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesTimeUpdateTimeRequest := _NodesTimeUpdateTimeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNodesTimeUpdateTimeRequest)

	if err != nil {
		return err
	}

	*o = NodesTimeUpdateTimeRequest(varNodesTimeUpdateTimeRequest)

	return err
}

type NullableNodesTimeUpdateTimeRequest struct {
	value *NodesTimeUpdateTimeRequest
	isSet bool
}

func (v NullableNodesTimeUpdateTimeRequest) Get() *NodesTimeUpdateTimeRequest {
	return v.value
}

func (v *NullableNodesTimeUpdateTimeRequest) Set(val *NodesTimeUpdateTimeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesTimeUpdateTimeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesTimeUpdateTimeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesTimeUpdateTimeRequest(val *NodesTimeUpdateTimeRequest) *NullableNodesTimeUpdateTimeRequest {
	return &NullableNodesTimeUpdateTimeRequest{value: val, isSet: true}
}

func (v NullableNodesTimeUpdateTimeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesTimeUpdateTimeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


