/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PdmPveRemotesKeyboardEnum the model 'PdmPveRemotesKeyboardEnum'
type PdmPveRemotesKeyboardEnum string

// List of PdmPveRemotesKeyboardEnum
const (
	PDMPVEREMOTESKEYBOARDENUM_DE PdmPveRemotesKeyboardEnum = "de"
	PDMPVEREMOTESKEYBOARDENUM_DE_CH PdmPveRemotesKeyboardEnum = "de-ch"
	PDMPVEREMOTESKEYBOARDENUM_DA PdmPveRemotesKeyboardEnum = "da"
	PDMPVEREMOTESKEYBOARDENUM_EN_GB PdmPveRemotesKeyboardEnum = "en-gb"
	PDMPVEREMOTESKEYBOARDENUM_EN_US PdmPveRemotesKeyboardEnum = "en-us"
	PDMPVEREMOTESKEYBOARDENUM_ES PdmPveRemotesKeyboardEnum = "es"
	PDMPVEREMOTESKEYBOARDENUM_FI PdmPveRemotesKeyboardEnum = "fi"
	PDMPVEREMOTESKEYBOARDENUM_FR PdmPveRemotesKeyboardEnum = "fr"
	PDMPVEREMOTESKEYBOARDENUM_FR_BE PdmPveRemotesKeyboardEnum = "fr-be"
	PDMPVEREMOTESKEYBOARDENUM_FR_CA PdmPveRemotesKeyboardEnum = "fr-ca"
	PDMPVEREMOTESKEYBOARDENUM_FR_CH PdmPveRemotesKeyboardEnum = "fr-ch"
	PDMPVEREMOTESKEYBOARDENUM_HU PdmPveRemotesKeyboardEnum = "hu"
	PDMPVEREMOTESKEYBOARDENUM_IS PdmPveRemotesKeyboardEnum = "is"
	PDMPVEREMOTESKEYBOARDENUM_IT PdmPveRemotesKeyboardEnum = "it"
	PDMPVEREMOTESKEYBOARDENUM_JA PdmPveRemotesKeyboardEnum = "ja"
	PDMPVEREMOTESKEYBOARDENUM_LT PdmPveRemotesKeyboardEnum = "lt"
	PDMPVEREMOTESKEYBOARDENUM_MK PdmPveRemotesKeyboardEnum = "mk"
	PDMPVEREMOTESKEYBOARDENUM_NL PdmPveRemotesKeyboardEnum = "nl"
	PDMPVEREMOTESKEYBOARDENUM_NO PdmPveRemotesKeyboardEnum = "no"
	PDMPVEREMOTESKEYBOARDENUM_PL PdmPveRemotesKeyboardEnum = "pl"
	PDMPVEREMOTESKEYBOARDENUM_PT PdmPveRemotesKeyboardEnum = "pt"
	PDMPVEREMOTESKEYBOARDENUM_PT_BR PdmPveRemotesKeyboardEnum = "pt-br"
	PDMPVEREMOTESKEYBOARDENUM_SV PdmPveRemotesKeyboardEnum = "sv"
	PDMPVEREMOTESKEYBOARDENUM_SL PdmPveRemotesKeyboardEnum = "sl"
	PDMPVEREMOTESKEYBOARDENUM_TR PdmPveRemotesKeyboardEnum = "tr"
)

// All allowed values of PdmPveRemotesKeyboardEnum enum
var AllowedPdmPveRemotesKeyboardEnumEnumValues = []PdmPveRemotesKeyboardEnum{
	"de",
	"de-ch",
	"da",
	"en-gb",
	"en-us",
	"es",
	"fi",
	"fr",
	"fr-be",
	"fr-ca",
	"fr-ch",
	"hu",
	"is",
	"it",
	"ja",
	"lt",
	"mk",
	"nl",
	"no",
	"pl",
	"pt",
	"pt-br",
	"sv",
	"sl",
	"tr",
}

func (v *PdmPveRemotesKeyboardEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PdmPveRemotesKeyboardEnum(value)
	for _, existing := range AllowedPdmPveRemotesKeyboardEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PdmPveRemotesKeyboardEnum", value)
}

// NewPdmPveRemotesKeyboardEnumFromValue returns a pointer to a valid PdmPveRemotesKeyboardEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPdmPveRemotesKeyboardEnumFromValue(v string) (*PdmPveRemotesKeyboardEnum, error) {
	ev := PdmPveRemotesKeyboardEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PdmPveRemotesKeyboardEnum: valid values are %v", v, AllowedPdmPveRemotesKeyboardEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PdmPveRemotesKeyboardEnum) IsValid() bool {
	for _, existing := range AllowedPdmPveRemotesKeyboardEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PdmPveRemotesKeyboardEnum value
func (v PdmPveRemotesKeyboardEnum) Ptr() *PdmPveRemotesKeyboardEnum {
	return &v
}

type NullablePdmPveRemotesKeyboardEnum struct {
	value *PdmPveRemotesKeyboardEnum
	isSet bool
}

func (v NullablePdmPveRemotesKeyboardEnum) Get() *PdmPveRemotesKeyboardEnum {
	return v.value
}

func (v *NullablePdmPveRemotesKeyboardEnum) Set(val *PdmPveRemotesKeyboardEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmPveRemotesKeyboardEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmPveRemotesKeyboardEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmPveRemotesKeyboardEnum(val *PdmPveRemotesKeyboardEnum) *NullablePdmPveRemotesKeyboardEnum {
	return &NullablePdmPveRemotesKeyboardEnum{value: val, isSet: true}
}

func (v NullablePdmPveRemotesKeyboardEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmPveRemotesKeyboardEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

