/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData{}

// ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData An RRD data series.
type ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData struct {

	// The data points.
	Data []float32 `json:"data"`

	// The resolution of the data points.
	Resolution int64 `json:"resolution"`

	// The UNIX epoch of the first data point.
	Start int64 `json:"start"`

	AdditionalProperties map[string]interface{}
}

type _ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData

// NewResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData instantiates a new ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData(data []float32, resolution int64, start int64) *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData {
	this := ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData{}
	this.Data = data
	this.Resolution = resolution
	this.Start = start
	return &this
}

// NewResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdDataWithDefaults instantiates a new ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdDataWithDefaults() *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData {
	this := ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData{}




	return &this
}


// GetData returns the Data field value
func (o *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) GetData() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) GetDataOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) SetData(v []float32) {
	o.Data = v
}


// GetResolution returns the Resolution field value
func (o *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) GetResolution() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value
// and a boolean to check if the value has been set.
func (o *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) GetResolutionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resolution, true
}

// SetResolution sets field value
func (o *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) SetResolution(v int64) {
	o.Resolution = v
}


// GetStart returns the Start field value
func (o *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) GetStart() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) GetStartOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) SetStart(v int64) {
	o.Start = v
}


func (o ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["data"] = o.Data
	
	toSerialize["resolution"] = o.Resolution
	
	toSerialize["start"] = o.Start
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"resolution",
		"start",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData := _ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData{}

	err = json.Unmarshal(data, &varResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData)

	if err != nil {
		return err
	}

	*o = ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData(varResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "resolution")
		delete(additionalProperties, "start")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData struct {
	value *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData
	isSet bool
}

func (v NullableResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) Get() *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData {
	return v.value
}

func (v *NullableResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) Set(val *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) {
	v.value = val
	v.isSet = true
}

func (v NullableResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) IsSet() bool {
	return v.isSet
}

func (v *NullableResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData(val *ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) *NullableResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData {
	return &NullableResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData{value: val, isSet: true}
}

func (v NullableResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


