/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PdmAmdSevField - struct for PdmAmdSevField
type PdmAmdSevField struct {
	PdmAmdSevConfig *PdmAmdSevConfig
	String *string
}

// PdmAmdSevConfigAsPdmAmdSevField is a convenience function that returns PdmAmdSevConfig wrapped in PdmAmdSevField
func PdmAmdSevConfigAsPdmAmdSevField(v *PdmAmdSevConfig) PdmAmdSevField {
	return PdmAmdSevField{
		PdmAmdSevConfig: v,
	}
}

// stringAsPdmAmdSevField is a convenience function that returns string wrapped in PdmAmdSevField
func StringAsPdmAmdSevField(v *string) PdmAmdSevField {
	return PdmAmdSevField{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PdmAmdSevField) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PdmAmdSevConfig
	err = newStrictDecoder(data).Decode(&dst.PdmAmdSevConfig)
	if err == nil {
		jsonPdmAmdSevConfig, _ := json.Marshal(dst.PdmAmdSevConfig)
		if string(jsonPdmAmdSevConfig) == "{}" { // empty struct
			dst.PdmAmdSevConfig = nil
		} else {
			if err = validator.Validate(dst.PdmAmdSevConfig); err != nil {
				dst.PdmAmdSevConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.PdmAmdSevConfig = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PdmAmdSevConfig = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PdmAmdSevField)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PdmAmdSevField)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PdmAmdSevField) MarshalJSON() ([]byte, error) {
	if src.PdmAmdSevConfig != nil {
		return json.Marshal(&src.PdmAmdSevConfig)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PdmAmdSevField) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PdmAmdSevConfig != nil {
		return obj.PdmAmdSevConfig
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PdmAmdSevField) GetActualInstanceValue() (interface{}) {
	if obj.PdmAmdSevConfig != nil {
		return *obj.PdmAmdSevConfig
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePdmAmdSevField struct {
	value *PdmAmdSevField
	isSet bool
}

func (v NullablePdmAmdSevField) Get() *PdmAmdSevField {
	return v.value
}

func (v *NullablePdmAmdSevField) Set(val *PdmAmdSevField) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmAmdSevField) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmAmdSevField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmAmdSevField(val *PdmAmdSevField) *NullablePdmAmdSevField {
	return &NullablePdmAmdSevField{value: val, isSet: true}
}

func (v NullablePdmAmdSevField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmAmdSevField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


