/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesGetJournalResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesGetJournalResponse{}

// NodesGetJournalResponse struct for NodesGetJournalResponse
type NodesGetJournalResponse struct {

	Data []string `json:"data"`

	// Optional total count, present for paginated list responses.
	Total *int32 `json:"total,omitempty"`

	// Optional change summary returned by some PUT operations (one entry per modified field).
	Changes map[string]interface{} `json:"changes,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _NodesGetJournalResponse NodesGetJournalResponse

// NewNodesGetJournalResponse instantiates a new NodesGetJournalResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesGetJournalResponse(data []string) *NodesGetJournalResponse {
	this := NodesGetJournalResponse{}
	this.Data = data
	return &this
}

// NewNodesGetJournalResponseWithDefaults instantiates a new NodesGetJournalResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesGetJournalResponseWithDefaults() *NodesGetJournalResponse {
	this := NodesGetJournalResponse{}




	return &this
}


// GetData returns the Data field value
func (o *NodesGetJournalResponse) GetData() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *NodesGetJournalResponse) GetDataOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *NodesGetJournalResponse) SetData(v []string) {
	o.Data = v
}


// GetTotal returns the Total field value if set, zero value otherwise.
func (o *NodesGetJournalResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesGetJournalResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *NodesGetJournalResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *NodesGetJournalResponse) SetTotal(v int32) {
	o.Total = &v
}


// GetChanges returns the Changes field value if set, zero value otherwise.
func (o *NodesGetJournalResponse) GetChanges() map[string]interface{} {
	if o == nil || IsNil(o.Changes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Changes
}

// GetChangesOk returns a tuple with the Changes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesGetJournalResponse) GetChangesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Changes) {
		return map[string]interface{}{}, false
	}
	return o.Changes, true
}

// HasChanges returns a boolean if a field has been set.
func (o *NodesGetJournalResponse) HasChanges() bool {
	if o != nil && !IsNil(o.Changes) {
		return true
	}

	return false
}

// SetChanges gets a reference to the given map[string]interface{} and assigns it to the Changes field.
func (o *NodesGetJournalResponse) SetChanges(v map[string]interface{}) {
	o.Changes = v
}


func (o NodesGetJournalResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesGetJournalResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["data"] = o.Data
	
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	
	if !IsNil(o.Changes) {
		toSerialize["changes"] = o.Changes
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesGetJournalResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesGetJournalResponse := _NodesGetJournalResponse{}

	err = json.Unmarshal(data, &varNodesGetJournalResponse)

	if err != nil {
		return err
	}

	*o = NodesGetJournalResponse(varNodesGetJournalResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "total")
		delete(additionalProperties, "changes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesGetJournalResponse struct {
	value *NodesGetJournalResponse
	isSet bool
}

func (v NullableNodesGetJournalResponse) Get() *NodesGetJournalResponse {
	return v.value
}

func (v *NullableNodesGetJournalResponse) Set(val *NodesGetJournalResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesGetJournalResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesGetJournalResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesGetJournalResponse(val *NodesGetJournalResponse) *NullableNodesGetJournalResponse {
	return &NullableNodesGetJournalResponse{value: val, isSet: true}
}

func (v NullableNodesGetJournalResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesGetJournalResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


