/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PdmPbsTypeEnum the model 'PdmPbsTypeEnum'
type PdmPbsTypeEnum string

// List of PdmPbsTypeEnum
const (
	PDMPBSTYPEENUM_PVE PdmPbsTypeEnum = "pve"
	PDMPBSTYPEENUM_PBS PdmPbsTypeEnum = "pbs"
)

// All allowed values of PdmPbsTypeEnum enum
var AllowedPdmPbsTypeEnumEnumValues = []PdmPbsTypeEnum{
	"pve",
	"pbs",
}

func (v *PdmPbsTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PdmPbsTypeEnum(value)
	for _, existing := range AllowedPdmPbsTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PdmPbsTypeEnum", value)
}

// NewPdmPbsTypeEnumFromValue returns a pointer to a valid PdmPbsTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPdmPbsTypeEnumFromValue(v string) (*PdmPbsTypeEnum, error) {
	ev := PdmPbsTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PdmPbsTypeEnum: valid values are %v", v, AllowedPdmPbsTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PdmPbsTypeEnum) IsValid() bool {
	for _, existing := range AllowedPdmPbsTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PdmPbsTypeEnum value
func (v PdmPbsTypeEnum) Ptr() *PdmPbsTypeEnum {
	return &v
}

type NullablePdmPbsTypeEnum struct {
	value *PdmPbsTypeEnum
	isSet bool
}

func (v NullablePdmPbsTypeEnum) Get() *PdmPbsTypeEnum {
	return v.value
}

func (v *NullablePdmPbsTypeEnum) Set(val *PdmPbsTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmPbsTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmPbsTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmPbsTypeEnum(val *PdmPbsTypeEnum) *NullablePdmPbsTypeEnum {
	return &NullablePdmPbsTypeEnum{value: val, isSet: true}
}

func (v NullablePdmPbsTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmPbsTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

