/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PdmError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PdmError{}

// PdmError Proxmox Datacenter Manager error envelope. Returned for all 4xx/5xx responses. `message` is always populated; `errors` is populated for validation failures with one entry per offending parameter.
type PdmError struct {

	Data interface{} `json:"data,omitempty"`

	Message string `json:"message"`

	Errors map[string]string `json:"errors,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _PdmError PdmError

// NewPdmError instantiates a new PdmError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPdmError(message string) *PdmError {
	this := PdmError{}
	this.Message = message
	return &this
}

// NewPdmErrorWithDefaults instantiates a new PdmError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPdmErrorWithDefaults() *PdmError {
	this := PdmError{}




	return &this
}


// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PdmError) GetData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PdmError) GetDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PdmError) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given interface{} and assigns it to the Data field.
func (o *PdmError) SetData(v interface{}) {
	o.Data = v
}


// GetMessage returns the Message field value
func (o *PdmError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *PdmError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *PdmError) SetMessage(v string) {
	o.Message = v
}


// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *PdmError) GetErrors() map[string]string {
	if o == nil || IsNil(o.Errors) {
		var ret map[string]string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PdmError) GetErrorsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return map[string]string{}, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *PdmError) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given map[string]string and assigns it to the Errors field.
func (o *PdmError) SetErrors(v map[string]string) {
	o.Errors = v
}


func (o PdmError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PdmError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	
	toSerialize["message"] = o.Message
	
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PdmError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPdmError := _PdmError{}

	err = json.Unmarshal(data, &varPdmError)

	if err != nil {
		return err
	}

	*o = PdmError(varPdmError)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "message")
		delete(additionalProperties, "errors")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePdmError struct {
	value *PdmError
	isSet bool
}

func (v NullablePdmError) Get() *PdmError {
	return v.value
}

func (v *NullablePdmError) Set(val *PdmError) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmError) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmError(val *PdmError) *NullablePdmError {
	return &NullablePdmError{value: val, isSet: true}
}

func (v NullablePdmError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


