/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PdmPveRemotesStatusEnum the model 'PdmPveRemotesStatusEnum'
type PdmPveRemotesStatusEnum string

// List of PdmPveRemotesStatusEnum
const (
	PDMPVEREMOTESSTATUSENUM_UNKNOWN PdmPveRemotesStatusEnum = "unknown"
	PDMPVEREMOTESSTATUSENUM_ONLINE PdmPveRemotesStatusEnum = "online"
	PDMPVEREMOTESSTATUSENUM_OFFLINE PdmPveRemotesStatusEnum = "offline"
)

// All allowed values of PdmPveRemotesStatusEnum enum
var AllowedPdmPveRemotesStatusEnumEnumValues = []PdmPveRemotesStatusEnum{
	"unknown",
	"online",
	"offline",
}

func (v *PdmPveRemotesStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PdmPveRemotesStatusEnum(value)
	for _, existing := range AllowedPdmPveRemotesStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PdmPveRemotesStatusEnum", value)
}

// NewPdmPveRemotesStatusEnumFromValue returns a pointer to a valid PdmPveRemotesStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPdmPveRemotesStatusEnumFromValue(v string) (*PdmPveRemotesStatusEnum, error) {
	ev := PdmPveRemotesStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PdmPveRemotesStatusEnum: valid values are %v", v, AllowedPdmPveRemotesStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PdmPveRemotesStatusEnum) IsValid() bool {
	for _, existing := range AllowedPdmPveRemotesStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PdmPveRemotesStatusEnum value
func (v PdmPveRemotesStatusEnum) Ptr() *PdmPveRemotesStatusEnum {
	return &v
}

type NullablePdmPveRemotesStatusEnum struct {
	value *PdmPveRemotesStatusEnum
	isSet bool
}

func (v NullablePdmPveRemotesStatusEnum) Get() *PdmPveRemotesStatusEnum {
	return v.value
}

func (v *NullablePdmPveRemotesStatusEnum) Set(val *PdmPveRemotesStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmPveRemotesStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmPveRemotesStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmPveRemotesStatusEnum(val *PdmPveRemotesStatusEnum) *NullablePdmPveRemotesStatusEnum {
	return &NullablePdmPveRemotesStatusEnum{value: val, isSet: true}
}

func (v NullablePdmPveRemotesStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmPveRemotesStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

