/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesTasksGetStatusResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesTasksGetStatusResponseData{}

// NodesTasksGetStatusResponseData struct for NodesTasksGetStatusResponseData
type NodesTasksGetStatusResponseData struct {

	// 'OK', 'Error: <msg>', or 'unknown'.
	Exitstatus *string `json:"exitstatus,omitempty"`

	// Worker ID (arbitrary ASCII string)
	Id *string `json:"id,omitempty"`

	// Node name (or 'localhost')
	Node string `json:"node" validate:"regexp=^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\\\-]*[a-zA-Z0-9])?)$"`

	// The Unix PID.
	Pid int64 `json:"pid"`

	// The Unix process start time from `/proc/pid/stat`
	Pstart int64 `json:"pstart"`

	// The task start time (Epoch)
	Starttime int64 `json:"starttime"`

	// 'running' or 'stopped'
	Status string `json:"status"`

	// The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full `Authid` for such use cases.
	Tokenid *string `json:"tokenid,omitempty" validate:"regexp=^(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*)$"`

	// Worker type (arbitrary ASCII string)
	Type string `json:"type"`

	// Unique Process/Task Identifier
	Upid string `json:"upid"`

	// User ID
	User string `json:"user" validate:"regexp=^(?:[^\\\\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*)$"`

	AdditionalProperties map[string]interface{}
}

type _NodesTasksGetStatusResponseData NodesTasksGetStatusResponseData

// NewNodesTasksGetStatusResponseData instantiates a new NodesTasksGetStatusResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesTasksGetStatusResponseData(node string, pid int64, pstart int64, starttime int64, status string, type_ string, upid string, user string) *NodesTasksGetStatusResponseData {
	this := NodesTasksGetStatusResponseData{}
	this.Node = node
	this.Pid = pid
	this.Pstart = pstart
	this.Starttime = starttime
	this.Status = status
	this.Type = type_
	this.Upid = upid
	this.User = user
	return &this
}

// NewNodesTasksGetStatusResponseDataWithDefaults instantiates a new NodesTasksGetStatusResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesTasksGetStatusResponseDataWithDefaults() *NodesTasksGetStatusResponseData {
	this := NodesTasksGetStatusResponseData{}












	return &this
}


// GetExitstatus returns the Exitstatus field value if set, zero value otherwise.
func (o *NodesTasksGetStatusResponseData) GetExitstatus() string {
	if o == nil || IsNil(o.Exitstatus) {
		var ret string
		return ret
	}
	return *o.Exitstatus
}

// GetExitstatusOk returns a tuple with the Exitstatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesTasksGetStatusResponseData) GetExitstatusOk() (*string, bool) {
	if o == nil || IsNil(o.Exitstatus) {
		return nil, false
	}
	return o.Exitstatus, true
}

// HasExitstatus returns a boolean if a field has been set.
func (o *NodesTasksGetStatusResponseData) HasExitstatus() bool {
	if o != nil && !IsNil(o.Exitstatus) {
		return true
	}

	return false
}

// SetExitstatus gets a reference to the given string and assigns it to the Exitstatus field.
func (o *NodesTasksGetStatusResponseData) SetExitstatus(v string) {
	o.Exitstatus = &v
}


// GetId returns the Id field value if set, zero value otherwise.
func (o *NodesTasksGetStatusResponseData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesTasksGetStatusResponseData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NodesTasksGetStatusResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NodesTasksGetStatusResponseData) SetId(v string) {
	o.Id = &v
}


// GetNode returns the Node field value
func (o *NodesTasksGetStatusResponseData) GetNode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Node
}

// GetNodeOk returns a tuple with the Node field value
// and a boolean to check if the value has been set.
func (o *NodesTasksGetStatusResponseData) GetNodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Node, true
}

// SetNode sets field value
func (o *NodesTasksGetStatusResponseData) SetNode(v string) {
	o.Node = v
}


// GetPid returns the Pid field value
func (o *NodesTasksGetStatusResponseData) GetPid() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Pid
}

// GetPidOk returns a tuple with the Pid field value
// and a boolean to check if the value has been set.
func (o *NodesTasksGetStatusResponseData) GetPidOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pid, true
}

// SetPid sets field value
func (o *NodesTasksGetStatusResponseData) SetPid(v int64) {
	o.Pid = v
}


// GetPstart returns the Pstart field value
func (o *NodesTasksGetStatusResponseData) GetPstart() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Pstart
}

// GetPstartOk returns a tuple with the Pstart field value
// and a boolean to check if the value has been set.
func (o *NodesTasksGetStatusResponseData) GetPstartOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pstart, true
}

// SetPstart sets field value
func (o *NodesTasksGetStatusResponseData) SetPstart(v int64) {
	o.Pstart = v
}


// GetStarttime returns the Starttime field value
func (o *NodesTasksGetStatusResponseData) GetStarttime() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Starttime
}

// GetStarttimeOk returns a tuple with the Starttime field value
// and a boolean to check if the value has been set.
func (o *NodesTasksGetStatusResponseData) GetStarttimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Starttime, true
}

// SetStarttime sets field value
func (o *NodesTasksGetStatusResponseData) SetStarttime(v int64) {
	o.Starttime = v
}


// GetStatus returns the Status field value
func (o *NodesTasksGetStatusResponseData) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *NodesTasksGetStatusResponseData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *NodesTasksGetStatusResponseData) SetStatus(v string) {
	o.Status = v
}


// GetTokenid returns the Tokenid field value if set, zero value otherwise.
func (o *NodesTasksGetStatusResponseData) GetTokenid() string {
	if o == nil || IsNil(o.Tokenid) {
		var ret string
		return ret
	}
	return *o.Tokenid
}

// GetTokenidOk returns a tuple with the Tokenid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesTasksGetStatusResponseData) GetTokenidOk() (*string, bool) {
	if o == nil || IsNil(o.Tokenid) {
		return nil, false
	}
	return o.Tokenid, true
}

// HasTokenid returns a boolean if a field has been set.
func (o *NodesTasksGetStatusResponseData) HasTokenid() bool {
	if o != nil && !IsNil(o.Tokenid) {
		return true
	}

	return false
}

// SetTokenid gets a reference to the given string and assigns it to the Tokenid field.
func (o *NodesTasksGetStatusResponseData) SetTokenid(v string) {
	o.Tokenid = &v
}


// GetType returns the Type field value
func (o *NodesTasksGetStatusResponseData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NodesTasksGetStatusResponseData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NodesTasksGetStatusResponseData) SetType(v string) {
	o.Type = v
}


// GetUpid returns the Upid field value
func (o *NodesTasksGetStatusResponseData) GetUpid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Upid
}

// GetUpidOk returns a tuple with the Upid field value
// and a boolean to check if the value has been set.
func (o *NodesTasksGetStatusResponseData) GetUpidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Upid, true
}

// SetUpid sets field value
func (o *NodesTasksGetStatusResponseData) SetUpid(v string) {
	o.Upid = v
}


// GetUser returns the User field value
func (o *NodesTasksGetStatusResponseData) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *NodesTasksGetStatusResponseData) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *NodesTasksGetStatusResponseData) SetUser(v string) {
	o.User = v
}


func (o NodesTasksGetStatusResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesTasksGetStatusResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Exitstatus) {
		toSerialize["exitstatus"] = o.Exitstatus
	}
	
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	
	toSerialize["node"] = o.Node
	
	toSerialize["pid"] = o.Pid
	
	toSerialize["pstart"] = o.Pstart
	
	toSerialize["starttime"] = o.Starttime
	
	toSerialize["status"] = o.Status
	
	if !IsNil(o.Tokenid) {
		toSerialize["tokenid"] = o.Tokenid
	}
	
	toSerialize["type"] = o.Type
	
	toSerialize["upid"] = o.Upid
	
	toSerialize["user"] = o.User
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesTasksGetStatusResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node",
		"pid",
		"pstart",
		"starttime",
		"status",
		"type",
		"upid",
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesTasksGetStatusResponseData := _NodesTasksGetStatusResponseData{}

	err = json.Unmarshal(data, &varNodesTasksGetStatusResponseData)

	if err != nil {
		return err
	}

	*o = NodesTasksGetStatusResponseData(varNodesTasksGetStatusResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "exitstatus")
		delete(additionalProperties, "id")
		delete(additionalProperties, "node")
		delete(additionalProperties, "pid")
		delete(additionalProperties, "pstart")
		delete(additionalProperties, "starttime")
		delete(additionalProperties, "status")
		delete(additionalProperties, "tokenid")
		delete(additionalProperties, "type")
		delete(additionalProperties, "upid")
		delete(additionalProperties, "user")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesTasksGetStatusResponseData struct {
	value *NodesTasksGetStatusResponseData
	isSet bool
}

func (v NullableNodesTasksGetStatusResponseData) Get() *NodesTasksGetStatusResponseData {
	return v.value
}

func (v *NullableNodesTasksGetStatusResponseData) Set(val *NodesTasksGetStatusResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesTasksGetStatusResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesTasksGetStatusResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesTasksGetStatusResponseData(val *NodesTasksGetStatusResponseData) *NullableNodesTasksGetStatusResponseData {
	return &NullableNodesTasksGetStatusResponseData{value: val, isSet: true}
}

func (v NullableNodesTasksGetStatusResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesTasksGetStatusResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


