/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PdmScsiField - struct for PdmScsiField
type PdmScsiField struct {
	PdmCdromConfig *PdmCdromConfig
	String *string
}

// PdmCdromConfigAsPdmScsiField is a convenience function that returns PdmCdromConfig wrapped in PdmScsiField
func PdmCdromConfigAsPdmScsiField(v *PdmCdromConfig) PdmScsiField {
	return PdmScsiField{
		PdmCdromConfig: v,
	}
}

// stringAsPdmScsiField is a convenience function that returns string wrapped in PdmScsiField
func StringAsPdmScsiField(v *string) PdmScsiField {
	return PdmScsiField{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PdmScsiField) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PdmCdromConfig
	err = newStrictDecoder(data).Decode(&dst.PdmCdromConfig)
	if err == nil {
		jsonPdmCdromConfig, _ := json.Marshal(dst.PdmCdromConfig)
		if string(jsonPdmCdromConfig) == "{}" { // empty struct
			dst.PdmCdromConfig = nil
		} else {
			if err = validator.Validate(dst.PdmCdromConfig); err != nil {
				dst.PdmCdromConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.PdmCdromConfig = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PdmCdromConfig = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PdmScsiField)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PdmScsiField)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PdmScsiField) MarshalJSON() ([]byte, error) {
	if src.PdmCdromConfig != nil {
		return json.Marshal(&src.PdmCdromConfig)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PdmScsiField) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PdmCdromConfig != nil {
		return obj.PdmCdromConfig
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PdmScsiField) GetActualInstanceValue() (interface{}) {
	if obj.PdmCdromConfig != nil {
		return *obj.PdmCdromConfig
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePdmScsiField struct {
	value *PdmScsiField
	isSet bool
}

func (v NullablePdmScsiField) Get() *PdmScsiField {
	return v.value
}

func (v *NullablePdmScsiField) Set(val *PdmScsiField) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmScsiField) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmScsiField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmScsiField(val *PdmScsiField) *NullablePdmScsiField {
	return &NullablePdmScsiField{value: val, isSet: true}
}

func (v NullablePdmScsiField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmScsiField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


