/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesAptGetRepositoriesResponseDataFilesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesAptGetRepositoriesResponseDataFilesInner{}

// NodesAptGetRepositoriesResponseDataFilesInner struct for NodesAptGetRepositoriesResponseDataFilesInner
type NodesAptGetRepositoriesResponseDataFilesInner struct {

	// The file content, if already parsed.
	Content *string `json:"content,omitempty"`

	// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty" validate:"regexp=^[a-f0-9]{64}$"`

	// The type of format used for an APT repository.
	FileType PdmFileTypeEnum `json:"file-type"`

	// The path to the file. If None, `contents` must be set directly.
	Path *string `json:"path,omitempty"`

	// List of APT repositories.
	Repositories []NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner `json:"repositories"`

	AdditionalProperties map[string]interface{}
}

type _NodesAptGetRepositoriesResponseDataFilesInner NodesAptGetRepositoriesResponseDataFilesInner

// NewNodesAptGetRepositoriesResponseDataFilesInner instantiates a new NodesAptGetRepositoriesResponseDataFilesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesAptGetRepositoriesResponseDataFilesInner(fileType PdmFileTypeEnum, repositories []NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner) *NodesAptGetRepositoriesResponseDataFilesInner {
	this := NodesAptGetRepositoriesResponseDataFilesInner{}
	this.FileType = fileType
	this.Repositories = repositories
	return &this
}

// NewNodesAptGetRepositoriesResponseDataFilesInnerWithDefaults instantiates a new NodesAptGetRepositoriesResponseDataFilesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesAptGetRepositoriesResponseDataFilesInnerWithDefaults() *NodesAptGetRepositoriesResponseDataFilesInner {
	this := NodesAptGetRepositoriesResponseDataFilesInner{}






	return &this
}


// GetContent returns the Content field value if set, zero value otherwise.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) SetContent(v string) {
	o.Content = &v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) SetDigest(v string) {
	o.Digest = &v
}


// GetFileType returns the FileType field value
func (o *NodesAptGetRepositoriesResponseDataFilesInner) GetFileType() PdmFileTypeEnum {
	if o == nil {
		var ret PdmFileTypeEnum
		return ret
	}

	return o.FileType
}

// GetFileTypeOk returns a tuple with the FileType field value
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) GetFileTypeOk() (*PdmFileTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileType, true
}

// SetFileType sets field value
func (o *NodesAptGetRepositoriesResponseDataFilesInner) SetFileType(v PdmFileTypeEnum) {
	o.FileType = v
}


// GetPath returns the Path field value if set, zero value otherwise.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) SetPath(v string) {
	o.Path = &v
}


// GetRepositories returns the Repositories field value
func (o *NodesAptGetRepositoriesResponseDataFilesInner) GetRepositories() []NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner {
	if o == nil {
		var ret []NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner
		return ret
	}

	return o.Repositories
}

// GetRepositoriesOk returns a tuple with the Repositories field value
// and a boolean to check if the value has been set.
func (o *NodesAptGetRepositoriesResponseDataFilesInner) GetRepositoriesOk() ([]NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Repositories, true
}

// SetRepositories sets field value
func (o *NodesAptGetRepositoriesResponseDataFilesInner) SetRepositories(v []NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner) {
	o.Repositories = v
}


func (o NodesAptGetRepositoriesResponseDataFilesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesAptGetRepositoriesResponseDataFilesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	toSerialize["file-type"] = o.FileType
	
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	
	toSerialize["repositories"] = o.Repositories
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesAptGetRepositoriesResponseDataFilesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file-type",
		"repositories",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesAptGetRepositoriesResponseDataFilesInner := _NodesAptGetRepositoriesResponseDataFilesInner{}

	err = json.Unmarshal(data, &varNodesAptGetRepositoriesResponseDataFilesInner)

	if err != nil {
		return err
	}

	*o = NodesAptGetRepositoriesResponseDataFilesInner(varNodesAptGetRepositoriesResponseDataFilesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "content")
		delete(additionalProperties, "digest")
		delete(additionalProperties, "file-type")
		delete(additionalProperties, "path")
		delete(additionalProperties, "repositories")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesAptGetRepositoriesResponseDataFilesInner struct {
	value *NodesAptGetRepositoriesResponseDataFilesInner
	isSet bool
}

func (v NullableNodesAptGetRepositoriesResponseDataFilesInner) Get() *NodesAptGetRepositoriesResponseDataFilesInner {
	return v.value
}

func (v *NullableNodesAptGetRepositoriesResponseDataFilesInner) Set(val *NodesAptGetRepositoriesResponseDataFilesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesAptGetRepositoriesResponseDataFilesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesAptGetRepositoriesResponseDataFilesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesAptGetRepositoriesResponseDataFilesInner(val *NodesAptGetRepositoriesResponseDataFilesInner) *NullableNodesAptGetRepositoriesResponseDataFilesInner {
	return &NullableNodesAptGetRepositoriesResponseDataFilesInner{value: val, isSet: true}
}

func (v NullableNodesAptGetRepositoriesResponseDataFilesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesAptGetRepositoriesResponseDataFilesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


