/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigAccessGetLdapResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigAccessGetLdapResponseDataInner{}

// ConfigAccessGetLdapResponseDataInner struct for ConfigAccessGetLdapResponseDataInner
type ConfigAccessGetLdapResponseDataInner struct {

	// LDAP Domain
	BaseDn string `json:"base-dn"`

	// LDAP Domain
	BindDn *string `json:"bind-dn,omitempty"`

	// CA certificate to use for the server. The path can point to either a file, or a directory. If it points to a file, the PEM-formatted X.509 certificate stored at the path will be added as a trusted certificate. If the path points to a directory, the directory replaces the system's default certificate store at `/etc/ssl/certs` - Every file in the directory will be loaded as a trusted certificate.
	Capath *string `json:"capath,omitempty"`

	// Comment.
	Comment *string `json:"comment,omitempty" validate:"regexp=^[[:^cntrl:]]*$"`

	// True if you want this to be the default realm selected on login.
	Default *bool `json:"default,omitempty"`

	// Custom LDAP search filter for user sync
	Filter *string `json:"filter,omitempty"`

	// LDAP connection type
	Mode *PdmModeEnum `json:"mode,omitempty"`

	// Port
	Port *int32 `json:"port,omitempty"`

	// Realm name.
	Realm string `json:"realm" validate:"regexp=^(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*)$"`

	// LDAP server address
	Server1 string `json:"server1"`

	// Fallback LDAP server address
	Server2 *string `json:"server2,omitempty"`

	// Comma-separated list of key=value pairs for specifying which LDAP attributes map to which peat user field. For example, to map the LDAP attribute ``mail`` to peat's ``email``, write ``email=mail``.
	SyncAttributes *PdmSyncAttributesField `json:"sync-attributes,omitempty"`

	// sync defaults options
	SyncDefaultsOptions *PdmSyncDefaultsOptionsField `json:"sync-defaults-options,omitempty"`

	// Username attribute. Used to map a ``userid`` to LDAP to an LDAP ``dn``.
	UserAttr string `json:"user-attr"`

	// Comma-separated list of allowed objectClass values for user synchronization. For instance, if ``user-classes`` is set to ``person,user``, then user synchronization will consider all LDAP entities where ``objectClass: person`` `or` ``objectClass: user``.
	UserClasses *PdmUserClassesField `json:"user-classes,omitempty"`

	// Verify server certificate
	Verify *bool `json:"verify,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _ConfigAccessGetLdapResponseDataInner ConfigAccessGetLdapResponseDataInner

// NewConfigAccessGetLdapResponseDataInner instantiates a new ConfigAccessGetLdapResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigAccessGetLdapResponseDataInner(baseDn string, realm string, server1 string, userAttr string) *ConfigAccessGetLdapResponseDataInner {
	this := ConfigAccessGetLdapResponseDataInner{}
	this.BaseDn = baseDn
	var default_ bool = 0
	this.Default = &default_
	var mode PdmModeEnum = PDMMODEENUM_LDAP
	this.Mode = &mode
	this.Realm = realm
	this.Server1 = server1
	this.UserAttr = userAttr
	var verify bool = 0
	this.Verify = &verify
	return &this
}

// NewConfigAccessGetLdapResponseDataInnerWithDefaults instantiates a new ConfigAccessGetLdapResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigAccessGetLdapResponseDataInnerWithDefaults() *ConfigAccessGetLdapResponseDataInner {
	this := ConfigAccessGetLdapResponseDataInner{}





	var default_ bool = 0
	this.Default = &default_


	var mode PdmModeEnum = PDMMODEENUM_LDAP
	this.Mode = &mode









	var verify bool = 0
	this.Verify = &verify

	return &this
}


// GetBaseDn returns the BaseDn field value
func (o *ConfigAccessGetLdapResponseDataInner) GetBaseDn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseDn
}

// GetBaseDnOk returns a tuple with the BaseDn field value
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetBaseDnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseDn, true
}

// SetBaseDn sets field value
func (o *ConfigAccessGetLdapResponseDataInner) SetBaseDn(v string) {
	o.BaseDn = v
}


// GetBindDn returns the BindDn field value if set, zero value otherwise.
func (o *ConfigAccessGetLdapResponseDataInner) GetBindDn() string {
	if o == nil || IsNil(o.BindDn) {
		var ret string
		return ret
	}
	return *o.BindDn
}

// GetBindDnOk returns a tuple with the BindDn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetBindDnOk() (*string, bool) {
	if o == nil || IsNil(o.BindDn) {
		return nil, false
	}
	return o.BindDn, true
}

// HasBindDn returns a boolean if a field has been set.
func (o *ConfigAccessGetLdapResponseDataInner) HasBindDn() bool {
	if o != nil && !IsNil(o.BindDn) {
		return true
	}

	return false
}

// SetBindDn gets a reference to the given string and assigns it to the BindDn field.
func (o *ConfigAccessGetLdapResponseDataInner) SetBindDn(v string) {
	o.BindDn = &v
}


// GetCapath returns the Capath field value if set, zero value otherwise.
func (o *ConfigAccessGetLdapResponseDataInner) GetCapath() string {
	if o == nil || IsNil(o.Capath) {
		var ret string
		return ret
	}
	return *o.Capath
}

// GetCapathOk returns a tuple with the Capath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetCapathOk() (*string, bool) {
	if o == nil || IsNil(o.Capath) {
		return nil, false
	}
	return o.Capath, true
}

// HasCapath returns a boolean if a field has been set.
func (o *ConfigAccessGetLdapResponseDataInner) HasCapath() bool {
	if o != nil && !IsNil(o.Capath) {
		return true
	}

	return false
}

// SetCapath gets a reference to the given string and assigns it to the Capath field.
func (o *ConfigAccessGetLdapResponseDataInner) SetCapath(v string) {
	o.Capath = &v
}


// GetComment returns the Comment field value if set, zero value otherwise.
func (o *ConfigAccessGetLdapResponseDataInner) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *ConfigAccessGetLdapResponseDataInner) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *ConfigAccessGetLdapResponseDataInner) SetComment(v string) {
	o.Comment = &v
}


// GetDefault returns the Default field value if set, zero value otherwise.
func (o *ConfigAccessGetLdapResponseDataInner) GetDefault() bool {
	if o == nil || IsNil(o.Default) {
		var ret bool
		return ret
	}
	return *o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.Default) {
		return nil, false
	}
	return o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *ConfigAccessGetLdapResponseDataInner) HasDefault() bool {
	if o != nil && !IsNil(o.Default) {
		return true
	}

	return false
}

// SetDefault gets a reference to the given bool and assigns it to the Default field.
func (o *ConfigAccessGetLdapResponseDataInner) SetDefault(v bool) {
	o.Default = &v
}


// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *ConfigAccessGetLdapResponseDataInner) GetFilter() string {
	if o == nil || IsNil(o.Filter) {
		var ret string
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetFilterOk() (*string, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *ConfigAccessGetLdapResponseDataInner) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given string and assigns it to the Filter field.
func (o *ConfigAccessGetLdapResponseDataInner) SetFilter(v string) {
	o.Filter = &v
}


// GetMode returns the Mode field value if set, zero value otherwise.
func (o *ConfigAccessGetLdapResponseDataInner) GetMode() PdmModeEnum {
	if o == nil || IsNil(o.Mode) {
		var ret PdmModeEnum
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetModeOk() (*PdmModeEnum, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *ConfigAccessGetLdapResponseDataInner) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given PdmModeEnum and assigns it to the Mode field.
func (o *ConfigAccessGetLdapResponseDataInner) SetMode(v PdmModeEnum) {
	o.Mode = &v
}


// GetPort returns the Port field value if set, zero value otherwise.
func (o *ConfigAccessGetLdapResponseDataInner) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *ConfigAccessGetLdapResponseDataInner) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *ConfigAccessGetLdapResponseDataInner) SetPort(v int32) {
	o.Port = &v
}


// GetRealm returns the Realm field value
func (o *ConfigAccessGetLdapResponseDataInner) GetRealm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Realm
}

// GetRealmOk returns a tuple with the Realm field value
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetRealmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Realm, true
}

// SetRealm sets field value
func (o *ConfigAccessGetLdapResponseDataInner) SetRealm(v string) {
	o.Realm = v
}


// GetServer1 returns the Server1 field value
func (o *ConfigAccessGetLdapResponseDataInner) GetServer1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Server1
}

// GetServer1Ok returns a tuple with the Server1 field value
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetServer1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Server1, true
}

// SetServer1 sets field value
func (o *ConfigAccessGetLdapResponseDataInner) SetServer1(v string) {
	o.Server1 = v
}


// GetServer2 returns the Server2 field value if set, zero value otherwise.
func (o *ConfigAccessGetLdapResponseDataInner) GetServer2() string {
	if o == nil || IsNil(o.Server2) {
		var ret string
		return ret
	}
	return *o.Server2
}

// GetServer2Ok returns a tuple with the Server2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetServer2Ok() (*string, bool) {
	if o == nil || IsNil(o.Server2) {
		return nil, false
	}
	return o.Server2, true
}

// HasServer2 returns a boolean if a field has been set.
func (o *ConfigAccessGetLdapResponseDataInner) HasServer2() bool {
	if o != nil && !IsNil(o.Server2) {
		return true
	}

	return false
}

// SetServer2 gets a reference to the given string and assigns it to the Server2 field.
func (o *ConfigAccessGetLdapResponseDataInner) SetServer2(v string) {
	o.Server2 = &v
}


// GetSyncAttributes returns the SyncAttributes field value if set, zero value otherwise.
func (o *ConfigAccessGetLdapResponseDataInner) GetSyncAttributes() PdmSyncAttributesField {
	if o == nil || IsNil(o.SyncAttributes) {
		var ret PdmSyncAttributesField
		return ret
	}
	return *o.SyncAttributes
}

// GetSyncAttributesOk returns a tuple with the SyncAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetSyncAttributesOk() (*PdmSyncAttributesField, bool) {
	if o == nil || IsNil(o.SyncAttributes) {
		return nil, false
	}
	return o.SyncAttributes, true
}

// HasSyncAttributes returns a boolean if a field has been set.
func (o *ConfigAccessGetLdapResponseDataInner) HasSyncAttributes() bool {
	if o != nil && !IsNil(o.SyncAttributes) {
		return true
	}

	return false
}

// SetSyncAttributes gets a reference to the given PdmSyncAttributesField and assigns it to the SyncAttributes field.
func (o *ConfigAccessGetLdapResponseDataInner) SetSyncAttributes(v PdmSyncAttributesField) {
	o.SyncAttributes = &v
}


// GetSyncDefaultsOptions returns the SyncDefaultsOptions field value if set, zero value otherwise.
func (o *ConfigAccessGetLdapResponseDataInner) GetSyncDefaultsOptions() PdmSyncDefaultsOptionsField {
	if o == nil || IsNil(o.SyncDefaultsOptions) {
		var ret PdmSyncDefaultsOptionsField
		return ret
	}
	return *o.SyncDefaultsOptions
}

// GetSyncDefaultsOptionsOk returns a tuple with the SyncDefaultsOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetSyncDefaultsOptionsOk() (*PdmSyncDefaultsOptionsField, bool) {
	if o == nil || IsNil(o.SyncDefaultsOptions) {
		return nil, false
	}
	return o.SyncDefaultsOptions, true
}

// HasSyncDefaultsOptions returns a boolean if a field has been set.
func (o *ConfigAccessGetLdapResponseDataInner) HasSyncDefaultsOptions() bool {
	if o != nil && !IsNil(o.SyncDefaultsOptions) {
		return true
	}

	return false
}

// SetSyncDefaultsOptions gets a reference to the given PdmSyncDefaultsOptionsField and assigns it to the SyncDefaultsOptions field.
func (o *ConfigAccessGetLdapResponseDataInner) SetSyncDefaultsOptions(v PdmSyncDefaultsOptionsField) {
	o.SyncDefaultsOptions = &v
}


// GetUserAttr returns the UserAttr field value
func (o *ConfigAccessGetLdapResponseDataInner) GetUserAttr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserAttr
}

// GetUserAttrOk returns a tuple with the UserAttr field value
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetUserAttrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserAttr, true
}

// SetUserAttr sets field value
func (o *ConfigAccessGetLdapResponseDataInner) SetUserAttr(v string) {
	o.UserAttr = v
}


// GetUserClasses returns the UserClasses field value if set, zero value otherwise.
func (o *ConfigAccessGetLdapResponseDataInner) GetUserClasses() PdmUserClassesField {
	if o == nil || IsNil(o.UserClasses) {
		var ret PdmUserClassesField
		return ret
	}
	return *o.UserClasses
}

// GetUserClassesOk returns a tuple with the UserClasses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetUserClassesOk() (*PdmUserClassesField, bool) {
	if o == nil || IsNil(o.UserClasses) {
		return nil, false
	}
	return o.UserClasses, true
}

// HasUserClasses returns a boolean if a field has been set.
func (o *ConfigAccessGetLdapResponseDataInner) HasUserClasses() bool {
	if o != nil && !IsNil(o.UserClasses) {
		return true
	}

	return false
}

// SetUserClasses gets a reference to the given PdmUserClassesField and assigns it to the UserClasses field.
func (o *ConfigAccessGetLdapResponseDataInner) SetUserClasses(v PdmUserClassesField) {
	o.UserClasses = &v
}


// GetVerify returns the Verify field value if set, zero value otherwise.
func (o *ConfigAccessGetLdapResponseDataInner) GetVerify() bool {
	if o == nil || IsNil(o.Verify) {
		var ret bool
		return ret
	}
	return *o.Verify
}

// GetVerifyOk returns a tuple with the Verify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetLdapResponseDataInner) GetVerifyOk() (*bool, bool) {
	if o == nil || IsNil(o.Verify) {
		return nil, false
	}
	return o.Verify, true
}

// HasVerify returns a boolean if a field has been set.
func (o *ConfigAccessGetLdapResponseDataInner) HasVerify() bool {
	if o != nil && !IsNil(o.Verify) {
		return true
	}

	return false
}

// SetVerify gets a reference to the given bool and assigns it to the Verify field.
func (o *ConfigAccessGetLdapResponseDataInner) SetVerify(v bool) {
	o.Verify = &v
}


func (o ConfigAccessGetLdapResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigAccessGetLdapResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["base-dn"] = o.BaseDn
	
	if !IsNil(o.BindDn) {
		toSerialize["bind-dn"] = o.BindDn
	}
	
	if !IsNil(o.Capath) {
		toSerialize["capath"] = o.Capath
	}
	
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	
	if !IsNil(o.Default) {
		toSerialize["default"] = o.Default
	}
	
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	
	toSerialize["realm"] = o.Realm
	
	toSerialize["server1"] = o.Server1
	
	if !IsNil(o.Server2) {
		toSerialize["server2"] = o.Server2
	}
	
	if !IsNil(o.SyncAttributes) {
		toSerialize["sync-attributes"] = o.SyncAttributes
	}
	
	if !IsNil(o.SyncDefaultsOptions) {
		toSerialize["sync-defaults-options"] = o.SyncDefaultsOptions
	}
	
	toSerialize["user-attr"] = o.UserAttr
	
	if !IsNil(o.UserClasses) {
		toSerialize["user-classes"] = o.UserClasses
	}
	
	if !IsNil(o.Verify) {
		toSerialize["verify"] = o.Verify
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigAccessGetLdapResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"base-dn",
		"realm",
		"server1",
		"user-attr",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigAccessGetLdapResponseDataInner := _ConfigAccessGetLdapResponseDataInner{}

	err = json.Unmarshal(data, &varConfigAccessGetLdapResponseDataInner)

	if err != nil {
		return err
	}

	*o = ConfigAccessGetLdapResponseDataInner(varConfigAccessGetLdapResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "base-dn")
		delete(additionalProperties, "bind-dn")
		delete(additionalProperties, "capath")
		delete(additionalProperties, "comment")
		delete(additionalProperties, "default")
		delete(additionalProperties, "filter")
		delete(additionalProperties, "mode")
		delete(additionalProperties, "port")
		delete(additionalProperties, "realm")
		delete(additionalProperties, "server1")
		delete(additionalProperties, "server2")
		delete(additionalProperties, "sync-attributes")
		delete(additionalProperties, "sync-defaults-options")
		delete(additionalProperties, "user-attr")
		delete(additionalProperties, "user-classes")
		delete(additionalProperties, "verify")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigAccessGetLdapResponseDataInner struct {
	value *ConfigAccessGetLdapResponseDataInner
	isSet bool
}

func (v NullableConfigAccessGetLdapResponseDataInner) Get() *ConfigAccessGetLdapResponseDataInner {
	return v.value
}

func (v *NullableConfigAccessGetLdapResponseDataInner) Set(val *ConfigAccessGetLdapResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigAccessGetLdapResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigAccessGetLdapResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigAccessGetLdapResponseDataInner(val *ConfigAccessGetLdapResponseDataInner) *NullableConfigAccessGetLdapResponseDataInner {
	return &NullableConfigAccessGetLdapResponseDataInner{value: val, isSet: true}
}

func (v NullableConfigAccessGetLdapResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigAccessGetLdapResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


