/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PdmItemsEnum the model 'PdmItemsEnum'
type PdmItemsEnum string

// List of PdmItemsEnum
const (
	PDMITEMSENUM_AMANDA PdmItemsEnum = "amanda"
	PDMITEMSENUM_FTP PdmItemsEnum = "ftp"
	PDMITEMSENUM_IRC PdmItemsEnum = "irc"
	PDMITEMSENUM_NETBIOS_NS PdmItemsEnum = "netbios-ns"
	PDMITEMSENUM_PPTP PdmItemsEnum = "pptp"
	PDMITEMSENUM_SANE PdmItemsEnum = "sane"
	PDMITEMSENUM_SIP PdmItemsEnum = "sip"
	PDMITEMSENUM_SNMP PdmItemsEnum = "snmp"
	PDMITEMSENUM_TFTP PdmItemsEnum = "tftp"
)

// All allowed values of PdmItemsEnum enum
var AllowedPdmItemsEnumEnumValues = []PdmItemsEnum{
	"amanda",
	"ftp",
	"irc",
	"netbios-ns",
	"pptp",
	"sane",
	"sip",
	"snmp",
	"tftp",
}

func (v *PdmItemsEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PdmItemsEnum(value)
	for _, existing := range AllowedPdmItemsEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PdmItemsEnum", value)
}

// NewPdmItemsEnumFromValue returns a pointer to a valid PdmItemsEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPdmItemsEnumFromValue(v string) (*PdmItemsEnum, error) {
	ev := PdmItemsEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PdmItemsEnum: valid values are %v", v, AllowedPdmItemsEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PdmItemsEnum) IsValid() bool {
	for _, existing := range AllowedPdmItemsEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PdmItemsEnum value
func (v PdmItemsEnum) Ptr() *PdmItemsEnum {
	return &v
}

type NullablePdmItemsEnum struct {
	value *PdmItemsEnum
	isSet bool
}

func (v NullablePdmItemsEnum) Get() *PdmItemsEnum {
	return v.value
}

func (v *NullablePdmItemsEnum) Set(val *PdmItemsEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmItemsEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmItemsEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmItemsEnum(val *PdmItemsEnum) *NullablePdmItemsEnum {
	return &NullablePdmItemsEnum{value: val, isSet: true}
}

func (v NullablePdmItemsEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmItemsEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

