/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PdmPveRemotesItemsEnum the model 'PdmPveRemotesItemsEnum'
type PdmPveRemotesItemsEnum string

// List of PdmPveRemotesItemsEnum
const (
	PDMPVEREMOTESITEMSENUM_BACKUP PdmPveRemotesItemsEnum = "backup"
	PDMPVEREMOTESITEMSENUM_IMAGES PdmPveRemotesItemsEnum = "images"
	PDMPVEREMOTESITEMSENUM_IMPORT PdmPveRemotesItemsEnum = "import"
	PDMPVEREMOTESITEMSENUM_ISO PdmPveRemotesItemsEnum = "iso"
	PDMPVEREMOTESITEMSENUM_NONE PdmPveRemotesItemsEnum = "none"
	PDMPVEREMOTESITEMSENUM_ROOTDIR PdmPveRemotesItemsEnum = "rootdir"
	PDMPVEREMOTESITEMSENUM_SNIPPETS PdmPveRemotesItemsEnum = "snippets"
	PDMPVEREMOTESITEMSENUM_VZTMPL PdmPveRemotesItemsEnum = "vztmpl"
)

// All allowed values of PdmPveRemotesItemsEnum enum
var AllowedPdmPveRemotesItemsEnumEnumValues = []PdmPveRemotesItemsEnum{
	"backup",
	"images",
	"import",
	"iso",
	"none",
	"rootdir",
	"snippets",
	"vztmpl",
}

func (v *PdmPveRemotesItemsEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PdmPveRemotesItemsEnum(value)
	for _, existing := range AllowedPdmPveRemotesItemsEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PdmPveRemotesItemsEnum", value)
}

// NewPdmPveRemotesItemsEnumFromValue returns a pointer to a valid PdmPveRemotesItemsEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPdmPveRemotesItemsEnumFromValue(v string) (*PdmPveRemotesItemsEnum, error) {
	ev := PdmPveRemotesItemsEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PdmPveRemotesItemsEnum: valid values are %v", v, AllowedPdmPveRemotesItemsEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PdmPveRemotesItemsEnum) IsValid() bool {
	for _, existing := range AllowedPdmPveRemotesItemsEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PdmPveRemotesItemsEnum value
func (v PdmPveRemotesItemsEnum) Ptr() *PdmPveRemotesItemsEnum {
	return &v
}

type NullablePdmPveRemotesItemsEnum struct {
	value *PdmPveRemotesItemsEnum
	isSet bool
}

func (v NullablePdmPveRemotesItemsEnum) Get() *PdmPveRemotesItemsEnum {
	return v.value
}

func (v *NullablePdmPveRemotesItemsEnum) Set(val *PdmPveRemotesItemsEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmPveRemotesItemsEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmPveRemotesItemsEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmPveRemotesItemsEnum(val *PdmPveRemotesItemsEnum) *NullablePdmPveRemotesItemsEnum {
	return &NullablePdmPveRemotesItemsEnum{value: val, isSet: true}
}

func (v NullablePdmPveRemotesItemsEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmPveRemotesItemsEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

