/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PdmAcmedomainField - struct for PdmAcmedomainField
type PdmAcmedomainField struct {
	PdmAcmedomainConfig *PdmAcmedomainConfig
	String *string
}

// PdmAcmedomainConfigAsPdmAcmedomainField is a convenience function that returns PdmAcmedomainConfig wrapped in PdmAcmedomainField
func PdmAcmedomainConfigAsPdmAcmedomainField(v *PdmAcmedomainConfig) PdmAcmedomainField {
	return PdmAcmedomainField{
		PdmAcmedomainConfig: v,
	}
}

// stringAsPdmAcmedomainField is a convenience function that returns string wrapped in PdmAcmedomainField
func StringAsPdmAcmedomainField(v *string) PdmAcmedomainField {
	return PdmAcmedomainField{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PdmAcmedomainField) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PdmAcmedomainConfig
	err = newStrictDecoder(data).Decode(&dst.PdmAcmedomainConfig)
	if err == nil {
		jsonPdmAcmedomainConfig, _ := json.Marshal(dst.PdmAcmedomainConfig)
		if string(jsonPdmAcmedomainConfig) == "{}" { // empty struct
			dst.PdmAcmedomainConfig = nil
		} else {
			if err = validator.Validate(dst.PdmAcmedomainConfig); err != nil {
				dst.PdmAcmedomainConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.PdmAcmedomainConfig = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PdmAcmedomainConfig = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PdmAcmedomainField)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PdmAcmedomainField)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PdmAcmedomainField) MarshalJSON() ([]byte, error) {
	if src.PdmAcmedomainConfig != nil {
		return json.Marshal(&src.PdmAcmedomainConfig)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PdmAcmedomainField) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PdmAcmedomainConfig != nil {
		return obj.PdmAcmedomainConfig
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PdmAcmedomainField) GetActualInstanceValue() (interface{}) {
	if obj.PdmAcmedomainConfig != nil {
		return *obj.PdmAcmedomainConfig
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePdmAcmedomainField struct {
	value *PdmAcmedomainField
	isSet bool
}

func (v NullablePdmAcmedomainField) Get() *PdmAcmedomainField {
	return v.value
}

func (v *NullablePdmAcmedomainField) Set(val *PdmAcmedomainField) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmAcmedomainField) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmAcmedomainField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmAcmedomainField(val *PdmAcmedomainField) *NullablePdmAcmedomainField {
	return &NullablePdmAcmedomainField{value: val, isSet: true}
}

func (v NullablePdmAcmedomainField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmAcmedomainField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


