/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the RemotesRemoteGetVersionResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemotesRemoteGetVersionResponseData{}

// RemotesRemoteGetVersionResponseData struct for RemotesRemoteGetVersionResponseData
type RemotesRemoteGetVersionResponseData struct {

	// The default console viewer to use.
	Console *PdmRemotesRemoteConsoleEnum `json:"console,omitempty"`

	// The current Proxmox VE point release in `x.y` format.
	Release string `json:"release"`

	// The short git revision from which this version was build.
	Repoid string `json:"repoid"`

	// The full pve-manager package version of this node.
	Version string `json:"version"`

	AdditionalProperties map[string]interface{}
}

type _RemotesRemoteGetVersionResponseData RemotesRemoteGetVersionResponseData

// NewRemotesRemoteGetVersionResponseData instantiates a new RemotesRemoteGetVersionResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemotesRemoteGetVersionResponseData(release string, repoid string, version string) *RemotesRemoteGetVersionResponseData {
	this := RemotesRemoteGetVersionResponseData{}
	this.Release = release
	this.Repoid = repoid
	this.Version = version
	return &this
}

// NewRemotesRemoteGetVersionResponseDataWithDefaults instantiates a new RemotesRemoteGetVersionResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemotesRemoteGetVersionResponseDataWithDefaults() *RemotesRemoteGetVersionResponseData {
	this := RemotesRemoteGetVersionResponseData{}





	return &this
}


// GetConsole returns the Console field value if set, zero value otherwise.
func (o *RemotesRemoteGetVersionResponseData) GetConsole() PdmRemotesRemoteConsoleEnum {
	if o == nil || IsNil(o.Console) {
		var ret PdmRemotesRemoteConsoleEnum
		return ret
	}
	return *o.Console
}

// GetConsoleOk returns a tuple with the Console field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemotesRemoteGetVersionResponseData) GetConsoleOk() (*PdmRemotesRemoteConsoleEnum, bool) {
	if o == nil || IsNil(o.Console) {
		return nil, false
	}
	return o.Console, true
}

// HasConsole returns a boolean if a field has been set.
func (o *RemotesRemoteGetVersionResponseData) HasConsole() bool {
	if o != nil && !IsNil(o.Console) {
		return true
	}

	return false
}

// SetConsole gets a reference to the given PdmRemotesRemoteConsoleEnum and assigns it to the Console field.
func (o *RemotesRemoteGetVersionResponseData) SetConsole(v PdmRemotesRemoteConsoleEnum) {
	o.Console = &v
}


// GetRelease returns the Release field value
func (o *RemotesRemoteGetVersionResponseData) GetRelease() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Release
}

// GetReleaseOk returns a tuple with the Release field value
// and a boolean to check if the value has been set.
func (o *RemotesRemoteGetVersionResponseData) GetReleaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Release, true
}

// SetRelease sets field value
func (o *RemotesRemoteGetVersionResponseData) SetRelease(v string) {
	o.Release = v
}


// GetRepoid returns the Repoid field value
func (o *RemotesRemoteGetVersionResponseData) GetRepoid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Repoid
}

// GetRepoidOk returns a tuple with the Repoid field value
// and a boolean to check if the value has been set.
func (o *RemotesRemoteGetVersionResponseData) GetRepoidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Repoid, true
}

// SetRepoid sets field value
func (o *RemotesRemoteGetVersionResponseData) SetRepoid(v string) {
	o.Repoid = v
}


// GetVersion returns the Version field value
func (o *RemotesRemoteGetVersionResponseData) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *RemotesRemoteGetVersionResponseData) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *RemotesRemoteGetVersionResponseData) SetVersion(v string) {
	o.Version = v
}


func (o RemotesRemoteGetVersionResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemotesRemoteGetVersionResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Console) {
		toSerialize["console"] = o.Console
	}
	
	toSerialize["release"] = o.Release
	
	toSerialize["repoid"] = o.Repoid
	
	toSerialize["version"] = o.Version
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RemotesRemoteGetVersionResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"release",
		"repoid",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemotesRemoteGetVersionResponseData := _RemotesRemoteGetVersionResponseData{}

	err = json.Unmarshal(data, &varRemotesRemoteGetVersionResponseData)

	if err != nil {
		return err
	}

	*o = RemotesRemoteGetVersionResponseData(varRemotesRemoteGetVersionResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "console")
		delete(additionalProperties, "release")
		delete(additionalProperties, "repoid")
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRemotesRemoteGetVersionResponseData struct {
	value *RemotesRemoteGetVersionResponseData
	isSet bool
}

func (v NullableRemotesRemoteGetVersionResponseData) Get() *RemotesRemoteGetVersionResponseData {
	return v.value
}

func (v *NullableRemotesRemoteGetVersionResponseData) Set(val *RemotesRemoteGetVersionResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableRemotesRemoteGetVersionResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableRemotesRemoteGetVersionResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemotesRemoteGetVersionResponseData(val *RemotesRemoteGetVersionResponseData) *NullableRemotesRemoteGetVersionResponseData {
	return &NullableRemotesRemoteGetVersionResponseData{value: val, isSet: true}
}

func (v NullableRemotesRemoteGetVersionResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemotesRemoteGetVersionResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


