/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AccessTfaGetTfaResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessTfaGetTfaResponseDataInner{}

// AccessTfaGetTfaResponseDataInner struct for AccessTfaGetTfaResponseDataInner
type AccessTfaGetTfaResponseDataInner struct {

	// TFA entries.
	Entries []AccessTfaGetTfaResponseDataInnerEntriesInner `json:"entries"`

	// If a user's second factor is blocked, this contains the block's expiration time.
	TfaLockedUntil *int64 `json:"tfa-locked-until,omitempty"`

	// The user is locked out of TOTP authentication.
	TotpLocked bool `json:"totp-locked"`

	// The user this entry belongs to.
	Userid string `json:"userid"`

	AdditionalProperties map[string]interface{}
}

type _AccessTfaGetTfaResponseDataInner AccessTfaGetTfaResponseDataInner

// NewAccessTfaGetTfaResponseDataInner instantiates a new AccessTfaGetTfaResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessTfaGetTfaResponseDataInner(entries []AccessTfaGetTfaResponseDataInnerEntriesInner, totpLocked bool, userid string) *AccessTfaGetTfaResponseDataInner {
	this := AccessTfaGetTfaResponseDataInner{}
	this.Entries = entries
	this.TotpLocked = totpLocked
	this.Userid = userid
	return &this
}

// NewAccessTfaGetTfaResponseDataInnerWithDefaults instantiates a new AccessTfaGetTfaResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessTfaGetTfaResponseDataInnerWithDefaults() *AccessTfaGetTfaResponseDataInner {
	this := AccessTfaGetTfaResponseDataInner{}





	return &this
}


// GetEntries returns the Entries field value
func (o *AccessTfaGetTfaResponseDataInner) GetEntries() []AccessTfaGetTfaResponseDataInnerEntriesInner {
	if o == nil {
		var ret []AccessTfaGetTfaResponseDataInnerEntriesInner
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *AccessTfaGetTfaResponseDataInner) GetEntriesOk() ([]AccessTfaGetTfaResponseDataInnerEntriesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *AccessTfaGetTfaResponseDataInner) SetEntries(v []AccessTfaGetTfaResponseDataInnerEntriesInner) {
	o.Entries = v
}


// GetTfaLockedUntil returns the TfaLockedUntil field value if set, zero value otherwise.
func (o *AccessTfaGetTfaResponseDataInner) GetTfaLockedUntil() int64 {
	if o == nil || IsNil(o.TfaLockedUntil) {
		var ret int64
		return ret
	}
	return *o.TfaLockedUntil
}

// GetTfaLockedUntilOk returns a tuple with the TfaLockedUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessTfaGetTfaResponseDataInner) GetTfaLockedUntilOk() (*int64, bool) {
	if o == nil || IsNil(o.TfaLockedUntil) {
		return nil, false
	}
	return o.TfaLockedUntil, true
}

// HasTfaLockedUntil returns a boolean if a field has been set.
func (o *AccessTfaGetTfaResponseDataInner) HasTfaLockedUntil() bool {
	if o != nil && !IsNil(o.TfaLockedUntil) {
		return true
	}

	return false
}

// SetTfaLockedUntil gets a reference to the given int64 and assigns it to the TfaLockedUntil field.
func (o *AccessTfaGetTfaResponseDataInner) SetTfaLockedUntil(v int64) {
	o.TfaLockedUntil = &v
}


// GetTotpLocked returns the TotpLocked field value
func (o *AccessTfaGetTfaResponseDataInner) GetTotpLocked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TotpLocked
}

// GetTotpLockedOk returns a tuple with the TotpLocked field value
// and a boolean to check if the value has been set.
func (o *AccessTfaGetTfaResponseDataInner) GetTotpLockedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotpLocked, true
}

// SetTotpLocked sets field value
func (o *AccessTfaGetTfaResponseDataInner) SetTotpLocked(v bool) {
	o.TotpLocked = v
}


// GetUserid returns the Userid field value
func (o *AccessTfaGetTfaResponseDataInner) GetUserid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Userid
}

// GetUseridOk returns a tuple with the Userid field value
// and a boolean to check if the value has been set.
func (o *AccessTfaGetTfaResponseDataInner) GetUseridOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Userid, true
}

// SetUserid sets field value
func (o *AccessTfaGetTfaResponseDataInner) SetUserid(v string) {
	o.Userid = v
}


func (o AccessTfaGetTfaResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessTfaGetTfaResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["entries"] = o.Entries
	
	if !IsNil(o.TfaLockedUntil) {
		toSerialize["tfa-locked-until"] = o.TfaLockedUntil
	}
	
	toSerialize["totp-locked"] = o.TotpLocked
	
	toSerialize["userid"] = o.Userid
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccessTfaGetTfaResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entries",
		"totp-locked",
		"userid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessTfaGetTfaResponseDataInner := _AccessTfaGetTfaResponseDataInner{}

	err = json.Unmarshal(data, &varAccessTfaGetTfaResponseDataInner)

	if err != nil {
		return err
	}

	*o = AccessTfaGetTfaResponseDataInner(varAccessTfaGetTfaResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "entries")
		delete(additionalProperties, "tfa-locked-until")
		delete(additionalProperties, "totp-locked")
		delete(additionalProperties, "userid")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccessTfaGetTfaResponseDataInner struct {
	value *AccessTfaGetTfaResponseDataInner
	isSet bool
}

func (v NullableAccessTfaGetTfaResponseDataInner) Get() *AccessTfaGetTfaResponseDataInner {
	return v.value
}

func (v *NullableAccessTfaGetTfaResponseDataInner) Set(val *AccessTfaGetTfaResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessTfaGetTfaResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessTfaGetTfaResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessTfaGetTfaResponseDataInner(val *AccessTfaGetTfaResponseDataInner) *NullableAccessTfaGetTfaResponseDataInner {
	return &NullableAccessTfaGetTfaResponseDataInner{value: val, isSet: true}
}

func (v NullableAccessTfaGetTfaResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessTfaGetTfaResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


