/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesCreateTermproxyResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesCreateTermproxyResponseData{}

// NodesCreateTermproxyResponseData struct for NodesCreateTermproxyResponseData
type NodesCreateTermproxyResponseData struct {

	Port string `json:"port"`

	Ticket string `json:"ticket"`

	Upid string `json:"upid"`

	User string `json:"user"`

	AdditionalProperties map[string]interface{}
}

type _NodesCreateTermproxyResponseData NodesCreateTermproxyResponseData

// NewNodesCreateTermproxyResponseData instantiates a new NodesCreateTermproxyResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesCreateTermproxyResponseData(port string, ticket string, upid string, user string) *NodesCreateTermproxyResponseData {
	this := NodesCreateTermproxyResponseData{}
	this.Port = port
	this.Ticket = ticket
	this.Upid = upid
	this.User = user
	return &this
}

// NewNodesCreateTermproxyResponseDataWithDefaults instantiates a new NodesCreateTermproxyResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesCreateTermproxyResponseDataWithDefaults() *NodesCreateTermproxyResponseData {
	this := NodesCreateTermproxyResponseData{}





	return &this
}


// GetPort returns the Port field value
func (o *NodesCreateTermproxyResponseData) GetPort() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *NodesCreateTermproxyResponseData) GetPortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *NodesCreateTermproxyResponseData) SetPort(v string) {
	o.Port = v
}


// GetTicket returns the Ticket field value
func (o *NodesCreateTermproxyResponseData) GetTicket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ticket
}

// GetTicketOk returns a tuple with the Ticket field value
// and a boolean to check if the value has been set.
func (o *NodesCreateTermproxyResponseData) GetTicketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ticket, true
}

// SetTicket sets field value
func (o *NodesCreateTermproxyResponseData) SetTicket(v string) {
	o.Ticket = v
}


// GetUpid returns the Upid field value
func (o *NodesCreateTermproxyResponseData) GetUpid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Upid
}

// GetUpidOk returns a tuple with the Upid field value
// and a boolean to check if the value has been set.
func (o *NodesCreateTermproxyResponseData) GetUpidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Upid, true
}

// SetUpid sets field value
func (o *NodesCreateTermproxyResponseData) SetUpid(v string) {
	o.Upid = v
}


// GetUser returns the User field value
func (o *NodesCreateTermproxyResponseData) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *NodesCreateTermproxyResponseData) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *NodesCreateTermproxyResponseData) SetUser(v string) {
	o.User = v
}


func (o NodesCreateTermproxyResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesCreateTermproxyResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["port"] = o.Port
	
	toSerialize["ticket"] = o.Ticket
	
	toSerialize["upid"] = o.Upid
	
	toSerialize["user"] = o.User
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesCreateTermproxyResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"port",
		"ticket",
		"upid",
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesCreateTermproxyResponseData := _NodesCreateTermproxyResponseData{}

	err = json.Unmarshal(data, &varNodesCreateTermproxyResponseData)

	if err != nil {
		return err
	}

	*o = NodesCreateTermproxyResponseData(varNodesCreateTermproxyResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "port")
		delete(additionalProperties, "ticket")
		delete(additionalProperties, "upid")
		delete(additionalProperties, "user")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesCreateTermproxyResponseData struct {
	value *NodesCreateTermproxyResponseData
	isSet bool
}

func (v NullableNodesCreateTermproxyResponseData) Get() *NodesCreateTermproxyResponseData {
	return v.value
}

func (v *NullableNodesCreateTermproxyResponseData) Set(val *NodesCreateTermproxyResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesCreateTermproxyResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesCreateTermproxyResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesCreateTermproxyResponseData(val *NodesCreateTermproxyResponseData) *NullableNodesCreateTermproxyResponseData {
	return &NullableNodesCreateTermproxyResponseData{value: val, isSet: true}
}

func (v NullableNodesCreateTermproxyResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesCreateTermproxyResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


