/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PbsRemotesGetDatastoreResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PbsRemotesGetDatastoreResponseDataInner{}

// PbsRemotesGetDatastoreResponseDataInner struct for PbsRemotesGetDatastoreResponseDataInner
type PbsRemotesGetDatastoreResponseDataInner struct {

	// Datastore backend config
	Backend *string `json:"backend,omitempty"`

	// The UUID of the filesystem partition for removable datastores.
	BackingDevice *string `json:"backing-device,omitempty" validate:"regexp=^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$"`

	// Comment.
	Comment *string `json:"comment,omitempty" validate:"regexp=^[[:^cntrl:]]*$"`

	// Run garbage collection job at specified schedule.
	GcSchedule *string `json:"gc-schedule,omitempty"`

	// Number of daily backups to keep.
	KeepDaily *int64 `json:"keep-daily,omitempty"`

	// Number of hourly backups to keep.
	KeepHourly *int64 `json:"keep-hourly,omitempty"`

	// Number of backups to keep.
	KeepLast *int64 `json:"keep-last,omitempty"`

	// Number of monthly backups to keep.
	KeepMonthly *int64 `json:"keep-monthly,omitempty"`

	// Number of weekly backups to keep.
	KeepWeekly *int64 `json:"keep-weekly,omitempty"`

	// Number of yearly backups to keep.
	KeepYearly *int64 `json:"keep-yearly,omitempty"`

	// Maintenance mode, type is either 'offline' or 'read-only', message should be enclosed in \"
	MaintenanceMode *PdmMaintenanceModeField `json:"maintenance-mode,omitempty"`

	// Datastore name.
	Name string `json:"name" validate:"regexp=^(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*)$"`

	// Configure how notifications for this datastore should be sent. `legacy-sendmail` sends email notifications to the user configured in `notify-user` via the system's `sendmail` executable. `notification-system` emits matchable notification events to the notification system.
	NotificationMode *PdmPbsRemotesNotificationModeEnum `json:"notification-mode,omitempty"`

	// Datastore notification setting, enum can be one of 'always', 'never', or 'error'.
	Notify *PdmNotifyField `json:"notify,omitempty"`

	// User ID
	NotifyUser *string `json:"notify-user,omitempty" validate:"regexp=^(?:[^\\\\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*)$"`

	// Either the absolute path to the datastore directory, or a relative on-device path for removable datastores.
	Path string `json:"path"`

	// Run prune job at specified schedule.
	PruneSchedule *string `json:"prune-schedule,omitempty"`

	// Datastore tuning options
	Tuning *PdmTuningField `json:"tuning,omitempty"`

	// If enabled, all new backups will be verified right after completion.
	VerifyNew *bool `json:"verify-new,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _PbsRemotesGetDatastoreResponseDataInner PbsRemotesGetDatastoreResponseDataInner

// NewPbsRemotesGetDatastoreResponseDataInner instantiates a new PbsRemotesGetDatastoreResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPbsRemotesGetDatastoreResponseDataInner(name string, path string) *PbsRemotesGetDatastoreResponseDataInner {
	this := PbsRemotesGetDatastoreResponseDataInner{}
	this.Name = name
	var notificationMode PdmPbsRemotesNotificationModeEnum = PDMPBSREMOTESNOTIFICATIONMODEENUM_NOTIFICATION_SYSTEM
	this.NotificationMode = &notificationMode
	this.Path = path
	return &this
}

// NewPbsRemotesGetDatastoreResponseDataInnerWithDefaults instantiates a new PbsRemotesGetDatastoreResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPbsRemotesGetDatastoreResponseDataInnerWithDefaults() *PbsRemotesGetDatastoreResponseDataInner {
	this := PbsRemotesGetDatastoreResponseDataInner{}













	var notificationMode PdmPbsRemotesNotificationModeEnum = PDMPBSREMOTESNOTIFICATIONMODEENUM_NOTIFICATION_SYSTEM
	this.NotificationMode = &notificationMode







	return &this
}


// GetBackend returns the Backend field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetBackend() string {
	if o == nil || IsNil(o.Backend) {
		var ret string
		return ret
	}
	return *o.Backend
}

// GetBackendOk returns a tuple with the Backend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetBackendOk() (*string, bool) {
	if o == nil || IsNil(o.Backend) {
		return nil, false
	}
	return o.Backend, true
}

// HasBackend returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasBackend() bool {
	if o != nil && !IsNil(o.Backend) {
		return true
	}

	return false
}

// SetBackend gets a reference to the given string and assigns it to the Backend field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetBackend(v string) {
	o.Backend = &v
}


// GetBackingDevice returns the BackingDevice field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetBackingDevice() string {
	if o == nil || IsNil(o.BackingDevice) {
		var ret string
		return ret
	}
	return *o.BackingDevice
}

// GetBackingDeviceOk returns a tuple with the BackingDevice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetBackingDeviceOk() (*string, bool) {
	if o == nil || IsNil(o.BackingDevice) {
		return nil, false
	}
	return o.BackingDevice, true
}

// HasBackingDevice returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasBackingDevice() bool {
	if o != nil && !IsNil(o.BackingDevice) {
		return true
	}

	return false
}

// SetBackingDevice gets a reference to the given string and assigns it to the BackingDevice field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetBackingDevice(v string) {
	o.BackingDevice = &v
}


// GetComment returns the Comment field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetComment(v string) {
	o.Comment = &v
}


// GetGcSchedule returns the GcSchedule field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetGcSchedule() string {
	if o == nil || IsNil(o.GcSchedule) {
		var ret string
		return ret
	}
	return *o.GcSchedule
}

// GetGcScheduleOk returns a tuple with the GcSchedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetGcScheduleOk() (*string, bool) {
	if o == nil || IsNil(o.GcSchedule) {
		return nil, false
	}
	return o.GcSchedule, true
}

// HasGcSchedule returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasGcSchedule() bool {
	if o != nil && !IsNil(o.GcSchedule) {
		return true
	}

	return false
}

// SetGcSchedule gets a reference to the given string and assigns it to the GcSchedule field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetGcSchedule(v string) {
	o.GcSchedule = &v
}


// GetKeepDaily returns the KeepDaily field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetKeepDaily() int64 {
	if o == nil || IsNil(o.KeepDaily) {
		var ret int64
		return ret
	}
	return *o.KeepDaily
}

// GetKeepDailyOk returns a tuple with the KeepDaily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetKeepDailyOk() (*int64, bool) {
	if o == nil || IsNil(o.KeepDaily) {
		return nil, false
	}
	return o.KeepDaily, true
}

// HasKeepDaily returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasKeepDaily() bool {
	if o != nil && !IsNil(o.KeepDaily) {
		return true
	}

	return false
}

// SetKeepDaily gets a reference to the given int64 and assigns it to the KeepDaily field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetKeepDaily(v int64) {
	o.KeepDaily = &v
}


// GetKeepHourly returns the KeepHourly field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetKeepHourly() int64 {
	if o == nil || IsNil(o.KeepHourly) {
		var ret int64
		return ret
	}
	return *o.KeepHourly
}

// GetKeepHourlyOk returns a tuple with the KeepHourly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetKeepHourlyOk() (*int64, bool) {
	if o == nil || IsNil(o.KeepHourly) {
		return nil, false
	}
	return o.KeepHourly, true
}

// HasKeepHourly returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasKeepHourly() bool {
	if o != nil && !IsNil(o.KeepHourly) {
		return true
	}

	return false
}

// SetKeepHourly gets a reference to the given int64 and assigns it to the KeepHourly field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetKeepHourly(v int64) {
	o.KeepHourly = &v
}


// GetKeepLast returns the KeepLast field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetKeepLast() int64 {
	if o == nil || IsNil(o.KeepLast) {
		var ret int64
		return ret
	}
	return *o.KeepLast
}

// GetKeepLastOk returns a tuple with the KeepLast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetKeepLastOk() (*int64, bool) {
	if o == nil || IsNil(o.KeepLast) {
		return nil, false
	}
	return o.KeepLast, true
}

// HasKeepLast returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasKeepLast() bool {
	if o != nil && !IsNil(o.KeepLast) {
		return true
	}

	return false
}

// SetKeepLast gets a reference to the given int64 and assigns it to the KeepLast field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetKeepLast(v int64) {
	o.KeepLast = &v
}


// GetKeepMonthly returns the KeepMonthly field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetKeepMonthly() int64 {
	if o == nil || IsNil(o.KeepMonthly) {
		var ret int64
		return ret
	}
	return *o.KeepMonthly
}

// GetKeepMonthlyOk returns a tuple with the KeepMonthly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetKeepMonthlyOk() (*int64, bool) {
	if o == nil || IsNil(o.KeepMonthly) {
		return nil, false
	}
	return o.KeepMonthly, true
}

// HasKeepMonthly returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasKeepMonthly() bool {
	if o != nil && !IsNil(o.KeepMonthly) {
		return true
	}

	return false
}

// SetKeepMonthly gets a reference to the given int64 and assigns it to the KeepMonthly field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetKeepMonthly(v int64) {
	o.KeepMonthly = &v
}


// GetKeepWeekly returns the KeepWeekly field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetKeepWeekly() int64 {
	if o == nil || IsNil(o.KeepWeekly) {
		var ret int64
		return ret
	}
	return *o.KeepWeekly
}

// GetKeepWeeklyOk returns a tuple with the KeepWeekly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetKeepWeeklyOk() (*int64, bool) {
	if o == nil || IsNil(o.KeepWeekly) {
		return nil, false
	}
	return o.KeepWeekly, true
}

// HasKeepWeekly returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasKeepWeekly() bool {
	if o != nil && !IsNil(o.KeepWeekly) {
		return true
	}

	return false
}

// SetKeepWeekly gets a reference to the given int64 and assigns it to the KeepWeekly field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetKeepWeekly(v int64) {
	o.KeepWeekly = &v
}


// GetKeepYearly returns the KeepYearly field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetKeepYearly() int64 {
	if o == nil || IsNil(o.KeepYearly) {
		var ret int64
		return ret
	}
	return *o.KeepYearly
}

// GetKeepYearlyOk returns a tuple with the KeepYearly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetKeepYearlyOk() (*int64, bool) {
	if o == nil || IsNil(o.KeepYearly) {
		return nil, false
	}
	return o.KeepYearly, true
}

// HasKeepYearly returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasKeepYearly() bool {
	if o != nil && !IsNil(o.KeepYearly) {
		return true
	}

	return false
}

// SetKeepYearly gets a reference to the given int64 and assigns it to the KeepYearly field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetKeepYearly(v int64) {
	o.KeepYearly = &v
}


// GetMaintenanceMode returns the MaintenanceMode field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetMaintenanceMode() PdmMaintenanceModeField {
	if o == nil || IsNil(o.MaintenanceMode) {
		var ret PdmMaintenanceModeField
		return ret
	}
	return *o.MaintenanceMode
}

// GetMaintenanceModeOk returns a tuple with the MaintenanceMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetMaintenanceModeOk() (*PdmMaintenanceModeField, bool) {
	if o == nil || IsNil(o.MaintenanceMode) {
		return nil, false
	}
	return o.MaintenanceMode, true
}

// HasMaintenanceMode returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasMaintenanceMode() bool {
	if o != nil && !IsNil(o.MaintenanceMode) {
		return true
	}

	return false
}

// SetMaintenanceMode gets a reference to the given PdmMaintenanceModeField and assigns it to the MaintenanceMode field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetMaintenanceMode(v PdmMaintenanceModeField) {
	o.MaintenanceMode = &v
}


// GetName returns the Name field value
func (o *PbsRemotesGetDatastoreResponseDataInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PbsRemotesGetDatastoreResponseDataInner) SetName(v string) {
	o.Name = v
}


// GetNotificationMode returns the NotificationMode field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetNotificationMode() PdmPbsRemotesNotificationModeEnum {
	if o == nil || IsNil(o.NotificationMode) {
		var ret PdmPbsRemotesNotificationModeEnum
		return ret
	}
	return *o.NotificationMode
}

// GetNotificationModeOk returns a tuple with the NotificationMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetNotificationModeOk() (*PdmPbsRemotesNotificationModeEnum, bool) {
	if o == nil || IsNil(o.NotificationMode) {
		return nil, false
	}
	return o.NotificationMode, true
}

// HasNotificationMode returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasNotificationMode() bool {
	if o != nil && !IsNil(o.NotificationMode) {
		return true
	}

	return false
}

// SetNotificationMode gets a reference to the given PdmPbsRemotesNotificationModeEnum and assigns it to the NotificationMode field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetNotificationMode(v PdmPbsRemotesNotificationModeEnum) {
	o.NotificationMode = &v
}


// GetNotify returns the Notify field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetNotify() PdmNotifyField {
	if o == nil || IsNil(o.Notify) {
		var ret PdmNotifyField
		return ret
	}
	return *o.Notify
}

// GetNotifyOk returns a tuple with the Notify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetNotifyOk() (*PdmNotifyField, bool) {
	if o == nil || IsNil(o.Notify) {
		return nil, false
	}
	return o.Notify, true
}

// HasNotify returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasNotify() bool {
	if o != nil && !IsNil(o.Notify) {
		return true
	}

	return false
}

// SetNotify gets a reference to the given PdmNotifyField and assigns it to the Notify field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetNotify(v PdmNotifyField) {
	o.Notify = &v
}


// GetNotifyUser returns the NotifyUser field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetNotifyUser() string {
	if o == nil || IsNil(o.NotifyUser) {
		var ret string
		return ret
	}
	return *o.NotifyUser
}

// GetNotifyUserOk returns a tuple with the NotifyUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetNotifyUserOk() (*string, bool) {
	if o == nil || IsNil(o.NotifyUser) {
		return nil, false
	}
	return o.NotifyUser, true
}

// HasNotifyUser returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasNotifyUser() bool {
	if o != nil && !IsNil(o.NotifyUser) {
		return true
	}

	return false
}

// SetNotifyUser gets a reference to the given string and assigns it to the NotifyUser field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetNotifyUser(v string) {
	o.NotifyUser = &v
}


// GetPath returns the Path field value
func (o *PbsRemotesGetDatastoreResponseDataInner) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *PbsRemotesGetDatastoreResponseDataInner) SetPath(v string) {
	o.Path = v
}


// GetPruneSchedule returns the PruneSchedule field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetPruneSchedule() string {
	if o == nil || IsNil(o.PruneSchedule) {
		var ret string
		return ret
	}
	return *o.PruneSchedule
}

// GetPruneScheduleOk returns a tuple with the PruneSchedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetPruneScheduleOk() (*string, bool) {
	if o == nil || IsNil(o.PruneSchedule) {
		return nil, false
	}
	return o.PruneSchedule, true
}

// HasPruneSchedule returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasPruneSchedule() bool {
	if o != nil && !IsNil(o.PruneSchedule) {
		return true
	}

	return false
}

// SetPruneSchedule gets a reference to the given string and assigns it to the PruneSchedule field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetPruneSchedule(v string) {
	o.PruneSchedule = &v
}


// GetTuning returns the Tuning field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetTuning() PdmTuningField {
	if o == nil || IsNil(o.Tuning) {
		var ret PdmTuningField
		return ret
	}
	return *o.Tuning
}

// GetTuningOk returns a tuple with the Tuning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetTuningOk() (*PdmTuningField, bool) {
	if o == nil || IsNil(o.Tuning) {
		return nil, false
	}
	return o.Tuning, true
}

// HasTuning returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasTuning() bool {
	if o != nil && !IsNil(o.Tuning) {
		return true
	}

	return false
}

// SetTuning gets a reference to the given PdmTuningField and assigns it to the Tuning field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetTuning(v PdmTuningField) {
	o.Tuning = &v
}


// GetVerifyNew returns the VerifyNew field value if set, zero value otherwise.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetVerifyNew() bool {
	if o == nil || IsNil(o.VerifyNew) {
		var ret bool
		return ret
	}
	return *o.VerifyNew
}

// GetVerifyNewOk returns a tuple with the VerifyNew field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) GetVerifyNewOk() (*bool, bool) {
	if o == nil || IsNil(o.VerifyNew) {
		return nil, false
	}
	return o.VerifyNew, true
}

// HasVerifyNew returns a boolean if a field has been set.
func (o *PbsRemotesGetDatastoreResponseDataInner) HasVerifyNew() bool {
	if o != nil && !IsNil(o.VerifyNew) {
		return true
	}

	return false
}

// SetVerifyNew gets a reference to the given bool and assigns it to the VerifyNew field.
func (o *PbsRemotesGetDatastoreResponseDataInner) SetVerifyNew(v bool) {
	o.VerifyNew = &v
}


func (o PbsRemotesGetDatastoreResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PbsRemotesGetDatastoreResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Backend) {
		toSerialize["backend"] = o.Backend
	}
	
	if !IsNil(o.BackingDevice) {
		toSerialize["backing-device"] = o.BackingDevice
	}
	
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	
	if !IsNil(o.GcSchedule) {
		toSerialize["gc-schedule"] = o.GcSchedule
	}
	
	if !IsNil(o.KeepDaily) {
		toSerialize["keep-daily"] = o.KeepDaily
	}
	
	if !IsNil(o.KeepHourly) {
		toSerialize["keep-hourly"] = o.KeepHourly
	}
	
	if !IsNil(o.KeepLast) {
		toSerialize["keep-last"] = o.KeepLast
	}
	
	if !IsNil(o.KeepMonthly) {
		toSerialize["keep-monthly"] = o.KeepMonthly
	}
	
	if !IsNil(o.KeepWeekly) {
		toSerialize["keep-weekly"] = o.KeepWeekly
	}
	
	if !IsNil(o.KeepYearly) {
		toSerialize["keep-yearly"] = o.KeepYearly
	}
	
	if !IsNil(o.MaintenanceMode) {
		toSerialize["maintenance-mode"] = o.MaintenanceMode
	}
	
	toSerialize["name"] = o.Name
	
	if !IsNil(o.NotificationMode) {
		toSerialize["notification-mode"] = o.NotificationMode
	}
	
	if !IsNil(o.Notify) {
		toSerialize["notify"] = o.Notify
	}
	
	if !IsNil(o.NotifyUser) {
		toSerialize["notify-user"] = o.NotifyUser
	}
	
	toSerialize["path"] = o.Path
	
	if !IsNil(o.PruneSchedule) {
		toSerialize["prune-schedule"] = o.PruneSchedule
	}
	
	if !IsNil(o.Tuning) {
		toSerialize["tuning"] = o.Tuning
	}
	
	if !IsNil(o.VerifyNew) {
		toSerialize["verify-new"] = o.VerifyNew
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PbsRemotesGetDatastoreResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPbsRemotesGetDatastoreResponseDataInner := _PbsRemotesGetDatastoreResponseDataInner{}

	err = json.Unmarshal(data, &varPbsRemotesGetDatastoreResponseDataInner)

	if err != nil {
		return err
	}

	*o = PbsRemotesGetDatastoreResponseDataInner(varPbsRemotesGetDatastoreResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "backend")
		delete(additionalProperties, "backing-device")
		delete(additionalProperties, "comment")
		delete(additionalProperties, "gc-schedule")
		delete(additionalProperties, "keep-daily")
		delete(additionalProperties, "keep-hourly")
		delete(additionalProperties, "keep-last")
		delete(additionalProperties, "keep-monthly")
		delete(additionalProperties, "keep-weekly")
		delete(additionalProperties, "keep-yearly")
		delete(additionalProperties, "maintenance-mode")
		delete(additionalProperties, "name")
		delete(additionalProperties, "notification-mode")
		delete(additionalProperties, "notify")
		delete(additionalProperties, "notify-user")
		delete(additionalProperties, "path")
		delete(additionalProperties, "prune-schedule")
		delete(additionalProperties, "tuning")
		delete(additionalProperties, "verify-new")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePbsRemotesGetDatastoreResponseDataInner struct {
	value *PbsRemotesGetDatastoreResponseDataInner
	isSet bool
}

func (v NullablePbsRemotesGetDatastoreResponseDataInner) Get() *PbsRemotesGetDatastoreResponseDataInner {
	return v.value
}

func (v *NullablePbsRemotesGetDatastoreResponseDataInner) Set(val *PbsRemotesGetDatastoreResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsRemotesGetDatastoreResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsRemotesGetDatastoreResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsRemotesGetDatastoreResponseDataInner(val *PbsRemotesGetDatastoreResponseDataInner) *NullablePbsRemotesGetDatastoreResponseDataInner {
	return &NullablePbsRemotesGetDatastoreResponseDataInner{value: val, isSet: true}
}

func (v NullablePbsRemotesGetDatastoreResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsRemotesGetDatastoreResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


