/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PdmCdromConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PdmCdromConfig{}

// PdmCdromConfig struct for PdmCdromConfig
type PdmCdromConfig struct {

	AdditionalPropertiesField interface{} `json:"additionalProperties"`

	DefaultKey interface{} `json:"default_key"`

	Description interface{} `json:"description"`

	Properties PdmPropertiesField `json:"properties"`

	Type interface{} `json:"type"`

}

type _PdmCdromConfig PdmCdromConfig

// NewPdmCdromConfig instantiates a new PdmCdromConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPdmCdromConfig(additionalPropertiesField interface{}, defaultKey interface{}, description interface{}, properties PdmPropertiesField, type_ interface{}) *PdmCdromConfig {
	this := PdmCdromConfig{}
	this.AdditionalPropertiesField = additionalPropertiesField
	this.DefaultKey = defaultKey
	this.Description = description
	this.Properties = properties
	this.Type = type_
	return &this
}

// NewPdmCdromConfigWithDefaults instantiates a new PdmCdromConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPdmCdromConfigWithDefaults() *PdmCdromConfig {
	this := PdmCdromConfig{}






	return &this
}


// GetAdditionalPropertiesField returns the AdditionalPropertiesField field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PdmCdromConfig) GetAdditionalPropertiesField() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.AdditionalPropertiesField
}

// GetAdditionalPropertiesFieldOk returns a tuple with the AdditionalPropertiesField field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PdmCdromConfig) GetAdditionalPropertiesFieldOk() (*interface{}, bool) {
	if o == nil || IsNil(o.AdditionalPropertiesField) {
		return nil, false
	}
	return &o.AdditionalPropertiesField, true
}

// SetAdditionalPropertiesField sets field value
func (o *PdmCdromConfig) SetAdditionalPropertiesField(v interface{}) {
	o.AdditionalPropertiesField = v
}


// GetDefaultKey returns the DefaultKey field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PdmCdromConfig) GetDefaultKey() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.DefaultKey
}

// GetDefaultKeyOk returns a tuple with the DefaultKey field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PdmCdromConfig) GetDefaultKeyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DefaultKey) {
		return nil, false
	}
	return &o.DefaultKey, true
}

// SetDefaultKey sets field value
func (o *PdmCdromConfig) SetDefaultKey(v interface{}) {
	o.DefaultKey = v
}


// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PdmCdromConfig) GetDescription() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PdmCdromConfig) GetDescriptionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PdmCdromConfig) SetDescription(v interface{}) {
	o.Description = v
}


// GetProperties returns the Properties field value
func (o *PdmCdromConfig) GetProperties() PdmPropertiesField {
	if o == nil {
		var ret PdmPropertiesField
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *PdmCdromConfig) GetPropertiesOk() (*PdmPropertiesField, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *PdmCdromConfig) SetProperties(v PdmPropertiesField) {
	o.Properties = v
}


// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PdmCdromConfig) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PdmCdromConfig) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PdmCdromConfig) SetType(v interface{}) {
	o.Type = v
}


func (o PdmCdromConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PdmCdromConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if o.AdditionalPropertiesField != nil {
		toSerialize["additionalProperties"] = o.AdditionalPropertiesField
	}
	
	if o.DefaultKey != nil {
		toSerialize["default_key"] = o.DefaultKey
	}
	
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	
	toSerialize["properties"] = o.Properties
	
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	
	return toSerialize, nil
}

func (o *PdmCdromConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"additionalProperties",
		"default_key",
		"description",
		"properties",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPdmCdromConfig := _PdmCdromConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPdmCdromConfig)

	if err != nil {
		return err
	}

	*o = PdmCdromConfig(varPdmCdromConfig)

	return err
}

type NullablePdmCdromConfig struct {
	value *PdmCdromConfig
	isSet bool
}

func (v NullablePdmCdromConfig) Get() *PdmCdromConfig {
	return v.value
}

func (v *NullablePdmCdromConfig) Set(val *PdmCdromConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmCdromConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmCdromConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmCdromConfig(val *PdmCdromConfig) *NullablePdmCdromConfig {
	return &NullablePdmCdromConfig{value: val, isSet: true}
}

func (v NullablePdmCdromConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmCdromConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


