/*
Proxmox Datacenter Manager API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PdmNodesNetworkInlineEnum the model 'PdmNodesNetworkInlineEnum'
type PdmNodesNetworkInlineEnum string

// List of PdmNodesNetworkInlineEnum
const (
	PDMNODESNETWORKINLINEENUM_CIDR PdmNodesNetworkInlineEnum = "cidr"
	PDMNODESNETWORKINLINEENUM_CIDR6 PdmNodesNetworkInlineEnum = "cidr6"
	PDMNODESNETWORKINLINEENUM_GATEWAY PdmNodesNetworkInlineEnum = "gateway"
	PDMNODESNETWORKINLINEENUM_GATEWAY6 PdmNodesNetworkInlineEnum = "gateway6"
	PDMNODESNETWORKINLINEENUM_METHOD PdmNodesNetworkInlineEnum = "method"
	PDMNODESNETWORKINLINEENUM_METHOD6 PdmNodesNetworkInlineEnum = "method6"
	PDMNODESNETWORKINLINEENUM_COMMENTS PdmNodesNetworkInlineEnum = "comments"
	PDMNODESNETWORKINLINEENUM_COMMENTS6 PdmNodesNetworkInlineEnum = "comments6"
	PDMNODESNETWORKINLINEENUM_MTU PdmNodesNetworkInlineEnum = "mtu"
	PDMNODESNETWORKINLINEENUM_AUTOSTART PdmNodesNetworkInlineEnum = "autostart"
	PDMNODESNETWORKINLINEENUM_BRIDGE_PORTS PdmNodesNetworkInlineEnum = "bridge_ports"
	PDMNODESNETWORKINLINEENUM_BRIDGE_VLAN_AWARE PdmNodesNetworkInlineEnum = "bridge_vlan_aware"
	PDMNODESNETWORKINLINEENUM_SLAVES PdmNodesNetworkInlineEnum = "slaves"
	PDMNODESNETWORKINLINEENUM_BOND_PRIMARY PdmNodesNetworkInlineEnum = "bond-primary"
	PDMNODESNETWORKINLINEENUM_BOND_XMIT_HASH_POLICY PdmNodesNetworkInlineEnum = "bond_xmit_hash_policy"
)

// All allowed values of PdmNodesNetworkInlineEnum enum
var AllowedPdmNodesNetworkInlineEnumEnumValues = []PdmNodesNetworkInlineEnum{
	"cidr",
	"cidr6",
	"gateway",
	"gateway6",
	"method",
	"method6",
	"comments",
	"comments6",
	"mtu",
	"autostart",
	"bridge_ports",
	"bridge_vlan_aware",
	"slaves",
	"bond-primary",
	"bond_xmit_hash_policy",
}

func (v *PdmNodesNetworkInlineEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PdmNodesNetworkInlineEnum(value)
	for _, existing := range AllowedPdmNodesNetworkInlineEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PdmNodesNetworkInlineEnum", value)
}

// NewPdmNodesNetworkInlineEnumFromValue returns a pointer to a valid PdmNodesNetworkInlineEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPdmNodesNetworkInlineEnumFromValue(v string) (*PdmNodesNetworkInlineEnum, error) {
	ev := PdmNodesNetworkInlineEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PdmNodesNetworkInlineEnum: valid values are %v", v, AllowedPdmNodesNetworkInlineEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PdmNodesNetworkInlineEnum) IsValid() bool {
	for _, existing := range AllowedPdmNodesNetworkInlineEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PdmNodesNetworkInlineEnum value
func (v PdmNodesNetworkInlineEnum) Ptr() *PdmNodesNetworkInlineEnum {
	return &v
}

type NullablePdmNodesNetworkInlineEnum struct {
	value *PdmNodesNetworkInlineEnum
	isSet bool
}

func (v NullablePdmNodesNetworkInlineEnum) Get() *PdmNodesNetworkInlineEnum {
	return v.value
}

func (v *NullablePdmNodesNetworkInlineEnum) Set(val *PdmNodesNetworkInlineEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePdmNodesNetworkInlineEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePdmNodesNetworkInlineEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdmNodesNetworkInlineEnum(val *PdmNodesNetworkInlineEnum) *NullablePdmNodesNetworkInlineEnum {
	return &NullablePdmNodesNetworkInlineEnum{value: val, isSet: true}
}

func (v NullablePdmNodesNetworkInlineEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdmNodesNetworkInlineEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

